/**
 * ASKA Hearth & Honey KPI report — creator submission dataset.
 * 47 verified activations across 45 unique creator channels.
 */

export type AskaRow = {
  creator: string;
  tier: "Silver" | "Bronze";
  followers: number | null;
  topPct: number | null;
  allTimeAvgCCV: number | null;
  langRank: string;
  language: string;
  avgViewers: number;
  peakViewers: number;
  hours: string;
  hoursNum: number;
  viewerHours: number;
  raisePlatforms: string;
  mainQuest: string;
  raiseTheHorn: string;
  skaldHighlight: string;
  meadHallRising: string;
  twitchtracker: string;
  rowCost: number;
};

const lang = (s: string): string => {
  const m = s.match(/[A-Za-z]+/g);
  return m ? m[m.length - 1] : "";
};

export const rows: AskaRow[] = [
  { creator: "Phenexa",             tier: "Silver", followers: 3577,  topPct: 1.11, allTimeAvgCCV: 21.4, langRank: "33218 English",   language: "English",    avgViewers: 18, peakViewers: 25, hours: "2h55",  hoursNum: 2.92,  viewerHours: 52.5,  raisePlatforms: "X / Twitter",         mainQuest: "https://www.twitch.tv/videos/2753723194?t=00h23m59s",        raiseTheHorn: "https://x.com/OfficialPhenexa/status/2046665562323828943",     skaldHighlight: "",                                                                            meadHallRising: "",   twitchtracker: "https://twitchtracker.com/phenexa/streams/316884599783",        rowCost: 50 },
  { creator: "UndoubtedlyLink",     tier: "Silver", followers: 2230,  topPct: 1.18, allTimeAvgCCV: 29.0, langRank: "35554 English",   language: "English",    avgViewers: 26, peakViewers: 31, hours: "2h03",  hoursNum: 2.05,  viewerHours: 53.3,  raisePlatforms: "X / Twitter",         mainQuest: "https://www.twitch.tv/videos/2755869380",                    raiseTheHorn: "https://x.com/UndoubtedlyLink/status/2047708862472479229",   skaldHighlight: "https://x.com/UndoubtedlyLink/status/2047708862472479229",                     meadHallRising: "",   twitchtracker: "https://twitchtracker.com/undoubtedlylink/streams/317131913574", rowCost: 50 },
  { creator: "Paschaolin",          tier: "Silver", followers: 4796,  topPct: 1.17, allTimeAvgCCV: 14.6, langRank: "4499 Portuguese", language: "Portuguese", avgViewers: 15, peakViewers: 25, hours: "6h14",  hoursNum: 6.23,  viewerHours: 93.5,  raisePlatforms: "Instagram",            mainQuest: "https://www.twitch.tv/videos/2753808484?t=00h08m05s",        raiseTheHorn: "https://www.instagram.com/p/DXhO9yTDnGb/",                  skaldHighlight: "",                                                                            meadHallRising: "",   twitchtracker: "https://twitchtracker.com/paschoalin/streams/317713082998",     rowCost: 50 },
  { creator: "ItsMischa",           tier: "Silver", followers: 645,   topPct: 0.68, allTimeAvgCCV: 26.9, langRank: "3145 German",     language: "German",     avgViewers: 20, peakViewers: 28, hours: "3h30",  hoursNum: 3.5,   viewerHours: 70.0,  raisePlatforms: "TikTok",              mainQuest: "https://www.twitch.tv/videos/2757357603",                    raiseTheHorn: "https://www.tiktok.com/@mishoots_gaming/video/7633100297031748897", skaldHighlight: "",                                                                       meadHallRising: "",   twitchtracker: "https://twitchtracker.com/mishoots/games/25751086",             rowCost: 50 },
  { creator: "LunariValkyrie",      tier: "Silver", followers: 16192, topPct: 1.32, allTimeAvgCCV: 18.3, langRank: "39969 English",   language: "English",    avgViewers: 22, peakViewers: 27, hours: "3h",    hoursNum: 3.0,   viewerHours: 66.0,  raisePlatforms: "X / Twitter",         mainQuest: "https://www.twitch.tv/videos/2753313122?t=03h53m03s",        raiseTheHorn: "https://x.com/LunariValkyrie/status/2046449807603208432",    skaldHighlight: "https://www.tiktok.com/@lunarivalkyrie/video/7631169828081962254",             meadHallRising: "",   twitchtracker: "https://twitchtracker.com/lunarivalkyrie/streams/316411079927", rowCost: 50 },
  { creator: "LordaCrisPlays",      tier: "Silver", followers: 1060,  topPct: 0.53, allTimeAvgCCV: 23.0, langRank: "15379 English",   language: "English",    avgViewers: 22, peakViewers: 28, hours: "2h15",  hoursNum: 2.25,  viewerHours: 49.5,  raisePlatforms: "X / Twitter",         mainQuest: "https://www.twitch.tv/videos/2754465172?t=4h5m36s",          raiseTheHorn: "https://x.com/Lordacris/status/2044935222634885568",         skaldHighlight: "",                                                                            meadHallRising: "",   twitchtracker: "https://twitchtracker.com/lordacrisplays/streams/315476039250", rowCost: 50 },
  { creator: "The_Games_Detective", tier: "Bronze", followers: 1087,  topPct: null, allTimeAvgCCV: null, langRank: "155123 English",  language: "English",    avgViewers: 6,  peakViewers: 8,  hours: "2h15",  hoursNum: 2.25,  viewerHours: 13.5,  raisePlatforms: "X / Twitter",         mainQuest: "https://youtube.com/live/H2ZefLYY16Q",                       raiseTheHorn: "https://x.com/TheGamesDet/status/2046652462061297899",       skaldHighlight: "",                                                                            meadHallRising: "",   twitchtracker: "",                                                              rowCost: 20 },
  { creator: "Maveco",              tier: "Silver", followers: 12068, topPct: 1.82, allTimeAvgCCV: 18.2, langRank: "6539 Portuguese", language: "Portuguese", avgViewers: 17, peakViewers: 26, hours: "2h25",  hoursNum: 2.42,  viewerHours: 41.08, raisePlatforms: "X / Twitter",         mainQuest: "https://www.twitch.tv/videos/2757434278?t=3h55m37s",         raiseTheHorn: "https://x.com/MavecoTwitch/status/2048437233904988446",      skaldHighlight: "",                                                                            meadHallRising: "",   twitchtracker: "https://twitchtracker.com/maveco/streams/317748520694",         rowCost: 50 },
  { creator: "Savage_Kai",          tier: "Silver", followers: 1521,  topPct: 3.74, allTimeAvgCCV: 12.7, langRank: "120579 English",  language: "English",    avgViewers: 15, peakViewers: 17, hours: "3h17",  hoursNum: 3.28,  viewerHours: 49.25, raisePlatforms: "",                     mainQuest: "https://www.twitch.tv/videos/2767248017",                    raiseTheHorn: "",                                                          skaldHighlight: "",                                                                            meadHallRising: "",   twitchtracker: "https://twitchtracker.com/savage_kai/streams/317289852006",     rowCost: 50 },
  { creator: "Capsuhi",             tier: "Bronze", followers: 379,   topPct: 3.82, allTimeAvgCCV: 14.4, langRank: "13297 French",    language: "French",     avgViewers: 5,  peakViewers: 5,  hours: "2h",    hoursNum: 2.0,   viewerHours: 10.0,  raisePlatforms: "X / Twitter",         mainQuest: "https://www.twitch.tv/videos/2754341337",                    raiseTheHorn: "https://x.com/Capsuhi/status/2046967113886159084",           skaldHighlight: "",                                                                            meadHallRising: "",   twitchtracker: "https://twitchtracker.com/capsuhi/streams/316531435492",        rowCost: 20 },
  { creator: "TheBuraticus",        tier: "Bronze", followers: 11233, topPct: 3.73, allTimeAvgCCV: 10.7, langRank: "880 Turkish",     language: "Turkish",    avgViewers: 11, peakViewers: 13, hours: "1h26",  hoursNum: 1.43,  viewerHours: 15.77, raisePlatforms: "",                     mainQuest: "https://www.twitch.tv/videos/2761850004",                    raiseTheHorn: "",                                                          skaldHighlight: "",                                                                            meadHallRising: "",   twitchtracker: "https://twitchtracker.com/theburaticus/streams/317212749158",   rowCost: 20 },
  { creator: "Paildry",             tier: "Silver", followers: 805,   topPct: 1.03, allTimeAvgCCV: 19.0, langRank: "4721 German",     language: "German",     avgViewers: 19, peakViewers: 23, hours: "2h50",  hoursNum: 2.83,  viewerHours: 53.83, raisePlatforms: "X / Twitter",         mainQuest: "https://www.twitch.tv/videos/2753427350",                    raiseTheHorn: "https://x.com/Paildry/status/2046582971885326558",           skaldHighlight: "",                                                                            meadHallRising: "",   twitchtracker: "https://twitchtracker.com/paildry/streams/316879426407",        rowCost: 50 },
  { creator: "Gshiba",              tier: "Silver", followers: 6254,  topPct: 0.22, allTimeAvgCCV: 81.7, langRank: "969 Portuguese",  language: "Portuguese", avgViewers: 81, peakViewers: 91, hours: "2h05",  hoursNum: 2.08,  viewerHours: 168.75,raisePlatforms: "YouTube",              mainQuest: "https://www.twitch.tv/videos/2758273102?t=1h5m31s",          raiseTheHorn: "https://www.youtube.com/shorts/1EftzJYXtY8",                skaldHighlight: "https://www.youtube.com/shorts/1EftzJYXtY8",                                  meadHallRising: "",   twitchtracker: "https://twitchtracker.com/gshiba/games/25751086",               rowCost: 50 },
  { creator: "Foythtv (1)",         tier: "Silver", followers: 9842,  topPct: 0.11, allTimeAvgCCV: 84.0, langRank: "472 Portuguese",  language: "Portuguese", avgViewers: 39, peakViewers: 90, hours: "2h39",  hoursNum: 2.65,  viewerHours: 103.35,raisePlatforms: "X / Twitter",         mainQuest: "https://www.twitch.tv/videos/2755190550",                    raiseTheHorn: "https://x.com/FoythTv/status/2047390056885690783",           skaldHighlight: "",                                                                            meadHallRising: "",   twitchtracker: "https://twitchtracker.com/foythtv/streams/317726122998",        rowCost: 50 },
  { creator: "fradda",              tier: "Bronze", followers: 852,   topPct: 4.5,  allTimeAvgCCV: 6.0,  langRank: "18523 English",   language: "English",    avgViewers: 8,  peakViewers: 9,  hours: "2h05",  hoursNum: 2.08,  viewerHours: 16.67, raisePlatforms: "",                     mainQuest: "https://www.twitch.tv/videos/2766989599",                    raiseTheHorn: "",                                                          skaldHighlight: "",                                                                            meadHallRising: "",   twitchtracker: "https://twitchtracker.com/fradda/streams/315597219049",         rowCost: 20 },
  { creator: "soulessiren",         tier: "Silver", followers: 1032,  topPct: 0.59, allTimeAvgCCV: 36.9, langRank: "18081 English",   language: "English",    avgViewers: 15, peakViewers: 18, hours: "3h20",  hoursNum: 3.33,  viewerHours: 50.0,  raisePlatforms: "Bluesky",              mainQuest: "https://www.twitch.tv/videos/2757597498",                    raiseTheHorn: "https://bsky.app/profile/soulessiren.bsky.social/post/3mkjko64hjc2y", skaldHighlight: "https://www.tiktok.com/@soulessiren/video/7633626826786524430",          meadHallRising: "",   twitchtracker: "https://twitchtracker.com/soulessiren/streams/318918919257",    rowCost: 50 },
  { creator: "BBrista",             tier: "Bronze", followers: null,  topPct: null, allTimeAvgCCV: null, langRank: "",                language: "",           avgViewers: 7,  peakViewers: 8,  hours: "1h05",  hoursNum: 1.08,  viewerHours: 7.58,  raisePlatforms: "X / Twitter",         mainQuest: "https://www.twitch.tv/videos/2754287712?t=02h44m31s",        raiseTheHorn: "https://x.com/xBBrisita/status/2046983501560291772",         skaldHighlight: "",                                                                            meadHallRising: "",   twitchtracker: "https://twitchtracker.com/bbrisita/streams/316530687970",       rowCost: 20 },
  { creator: "Elllandria",          tier: "Silver", followers: 7556,  topPct: 0.35, allTimeAvgCCV: 46.8, langRank: "1513 Portuguese", language: "Portuguese", avgViewers: 25, peakViewers: 32, hours: "2h42",  hoursNum: 2.7,   viewerHours: 67.5,  raisePlatforms: "X / Twitter",         mainQuest: "https://www.twitch.tv/videos/2753470899",                    raiseTheHorn: "https://x.com/elllandria/status/2046552590440075455",        skaldHighlight: "https://x.com/elllandria/status/2046617032209174684",                         meadHallRising: "",   twitchtracker: "https://twitchtracker.com/elllandria/games/25751086",           rowCost: 50 },
  { creator: "SadWrathProduction",  tier: "Silver", followers: 1361,  topPct: 0.59, allTimeAvgCCV: 30.0, langRank: "2086 French",     language: "French",     avgViewers: 38, peakViewers: 44, hours: "4h15",  hoursNum: 4.25,  viewerHours: 161.5, raisePlatforms: "YouTube",              mainQuest: "https://www.twitch.tv/videos/2757564121",                    raiseTheHorn: "https://www.youtube.com/shorts/u1gcVc89Opk",                skaldHighlight: "",                                                                            meadHallRising: "",   twitchtracker: "https://twitchtracker.com/sadwrathproduction/games/25751086",   rowCost: 50 },
  { creator: "Eyklor",              tier: "Silver", followers: 511,   topPct: 1.45, allTimeAvgCCV: 16.9, langRank: "5027 French",     language: "French",     avgViewers: 20, peakViewers: 41, hours: "4h25",  hoursNum: 4.42,  viewerHours: 88.33, raisePlatforms: "TikTok",              mainQuest: "https://www.twitch.tv/videos/2757785755",                    raiseTheHorn: "https://www.tiktok.com/@eyklorju/video/7633163273394851094", skaldHighlight: "https://www.tiktok.com/@eyklorju/video/7633163273394851094",                  meadHallRising: "",   twitchtracker: "https://twitchtracker.com/eyklor",                              rowCost: 50 },
  { creator: "FabetaGames",         tier: "Silver", followers: 699,   topPct: 2.84, allTimeAvgCCV: 14.7, langRank: "9372 Portuguese", language: "Portuguese", avgViewers: 35, peakViewers: 50, hours: "2h37",  hoursNum: 2.62,  viewerHours: 91.58, raisePlatforms: "Instagram",            mainQuest: "https://www.twitch.tv/videos/2756929873",                    raiseTheHorn: "https://www.instagram.com/p/DXm3YQ_GewM/",                  skaldHighlight: "https://www.tiktok.com/@fabetagames/video/7633207186952408341",               meadHallRising: "Yes",twitchtracker: "https://twitchtracker.com/fabetagames/streams/317873631732",    rowCost: 50 },
  { creator: "Haouanubis",          tier: "Silver", followers: 540,   topPct: 2.18, allTimeAvgCCV: 29.2, langRank: "68105 English",   language: "English",    avgViewers: 30, peakViewers: 33, hours: "2h05",  hoursNum: 2.08,  viewerHours: 62.5,  raisePlatforms: "X / Twitter",         mainQuest: "https://www.twitch.tv/videos/2755869255",                    raiseTheHorn: "https://x.com/PharaohAnubis/status/2047709453240115402",     skaldHighlight: "https://x.com/PharaohAnubis/status/2047709453240115402",                      meadHallRising: "",   twitchtracker: "https://twitchtracker.com/haouanubis/streams/316591572451",     rowCost: 50 },
  { creator: "Velko_Live",          tier: "Silver", followers: 904,   topPct: 1.37, allTimeAvgCCV: 14.6, langRank: "41337 English",   language: "English",    avgViewers: 15, peakViewers: 17, hours: "5h26",  hoursNum: 5.43,  viewerHours: 81.5,  raisePlatforms: "X / Twitter",         mainQuest: "https://www.twitch.tv/videos/2753514165",                    raiseTheHorn: "https://x.com/VelizarPetrov2/status/2046929324859703318",    skaldHighlight: "",                                                                            meadHallRising: "",   twitchtracker: "https://twitchtracker.com/velko_live/streams/317036947301",     rowCost: 50 },
  { creator: "UmbritaC",            tier: "Silver", followers: 2768,  topPct: 2.2,  allTimeAvgCCV: 17.1, langRank: "112 Romanian",    language: "Romanian",   avgViewers: 27, peakViewers: 40, hours: "2h10",  hoursNum: 2.17,  viewerHours: 58.5,  raisePlatforms: "X / Twitter",         mainQuest: "https://www.twitch.tv/videos/2758362125?t=0h46m4s",          raiseTheHorn: "https://x.com/UmbritaC/status/2051200654757200236",          skaldHighlight: "https://x.com/UmbritaC/status/2045893485144781258",                           meadHallRising: "",   twitchtracker: "https://twitchtracker.com/umbritac/streams/317166126438",       rowCost: 50 },
  { creator: "Labsy",               tier: "Bronze", followers: 653,   topPct: 3.72, allTimeAvgCCV: 9.4,  langRank: "14033 French",    language: "French",     avgViewers: 7,  peakViewers: 9,  hours: "2h48",  hoursNum: 2.8,   viewerHours: 19.6,  raisePlatforms: "Instagram",            mainQuest: "https://www.twitch.tv/videos/2754336810",                    raiseTheHorn: "https://www.instagram.com/p/DXZSQ8cjAtC/",                  skaldHighlight: "",                                                                            meadHallRising: "",   twitchtracker: "https://twitchtracker.com/labsy/streams/316557567332",          rowCost: 20 },
  { creator: "SchrodingerKitten",   tier: "Silver", followers: 2517,  topPct: 1.27, allTimeAvgCCV: 17.2, langRank: "4378 French",     language: "French",     avgViewers: 18, peakViewers: 24, hours: "3h40",  hoursNum: 3.67,  viewerHours: 66.0,  raisePlatforms: "Bluesky",              mainQuest: "https://www.twitch.tv/videos/2754280282",                    raiseTheHorn: "https://bsky.app/profile/schrodingerkitten.bsky.social/post/3mk3khj7f4c2j", skaldHighlight: "",                                                                  meadHallRising: "",   twitchtracker: "https://twitchtracker.com/schrodingerkitten/games/25751086",    rowCost: 50 },
  { creator: "TattyHikari",         tier: "Silver", followers: 4761,  topPct: 0.6,  allTimeAvgCCV: 37.3, langRank: "2342 Portuguese", language: "Portuguese", avgViewers: 22, peakViewers: 34, hours: "4h26",  hoursNum: 4.43,  viewerHours: 97.53, raisePlatforms: "Instagram",            mainQuest: "https://www.twitch.tv/videos/2756381543",                    raiseTheHorn: "https://www.instagram.com/p/DXiU9fJFVgi",                   skaldHighlight: "",                                                                            meadHallRising: "",   twitchtracker: "https://twitchtracker.com/tattyhikari/streams/317809858549",    rowCost: 50 },
  { creator: "Shalalaka",           tier: "Silver", followers: 14150, topPct: 0.34, allTimeAvgCCV: 37.3, langRank: "1448 Portuguese", language: "Portuguese", avgViewers: 45, peakViewers: 49, hours: "2h05",  hoursNum: 2.08,  viewerHours: 93.75, raisePlatforms: "X / Twitter",         mainQuest: "https://www.twitch.tv/videos/2755307758?t=05h33m31s",        raiseTheHorn: "https://x.com/cidadeSHALALAKA/status/2047476282523324799",   skaldHighlight: "",                                                                            meadHallRising: "",   twitchtracker: "https://twitchtracker.com/shalalaka/streams/317726944118",      rowCost: 50 },
  { creator: "Toky",                tier: "Silver", followers: 25872, topPct: 1.8,  allTimeAvgCCV: 26.4, langRank: "55394 English",   language: "English",    avgViewers: 15, peakViewers: 18, hours: "2h43",  hoursNum: 2.72,  viewerHours: 40.75, raisePlatforms: "X / Twitter",         mainQuest: "https://www.twitch.tv/videos/2754630019",                    raiseTheHorn: "https://x.com/ToKymonGrey/status/2047072618524610744",       skaldHighlight: "",                                                                            meadHallRising: "",   twitchtracker: "https://twitchtracker.com/toky/games/25751086",                 rowCost: 50 },
  { creator: "Ser Bucky",           tier: "Silver", followers: null,  topPct: null, allTimeAvgCCV: null, langRank: "",                language: "",           avgViewers: 19, peakViewers: 23, hours: "2h30",  hoursNum: 2.5,   viewerHours: 47.5,  raisePlatforms: "",                     mainQuest: "https://www.twitch.tv/videos/2757685780",                    raiseTheHorn: "",                                                          skaldHighlight: "",                                                                            meadHallRising: "Yes",twitchtracker: "https://twitchtracker.com/serbucky/streams/317562901719",       rowCost: 50 },
  { creator: "MaekaAmaya",          tier: "Silver", followers: null,  topPct: null, allTimeAvgCCV: null, langRank: "",                language: "",           avgViewers: 22, peakViewers: 31, hours: "4h21",  hoursNum: 4.35,  viewerHours: 95.7,  raisePlatforms: "X / Twitter",         mainQuest: "https://www.twitch.tv/videos/2754423801",                    raiseTheHorn: "https://x.com/MaekaAmaya/status/2046610169220476969",        skaldHighlight: "",                                                                            meadHallRising: "",   twitchtracker: "https://twitchtracker.com/maekaamaya",                          rowCost: 50 },
  { creator: "KamilCesaro",         tier: "Silver", followers: 667,   topPct: 0.81, allTimeAvgCCV: 28.5, langRank: "23851 English",   language: "English",    avgViewers: 22, peakViewers: 34, hours: "2h30",  hoursNum: 2.5,   viewerHours: 55.0,  raisePlatforms: "X / Twitter",         mainQuest: "https://www.twitch.tv/videos/2755706705",                    raiseTheHorn: "https://x.com/kamilcesaro1/status/2047713516107264054",      skaldHighlight: "",                                                                            meadHallRising: "",   twitchtracker: "https://twitchtracker.com/kamilcesaro/games/25751086",          rowCost: 50 },
  { creator: "Foythtv (2)",         tier: "Silver", followers: 9842,  topPct: 0.11, allTimeAvgCCV: 84.0, langRank: "472 Portuguese",  language: "Portuguese", avgViewers: 41, peakViewers: 90, hours: "2h24",  hoursNum: 2.4,   viewerHours: 98.4,  raisePlatforms: "",                     mainQuest: "https://www.twitch.tv/videos/2755190550",                    raiseTheHorn: "",                                                          skaldHighlight: "",                                                                            meadHallRising: "",   twitchtracker: "https://twitchtracker.com/foythtv/streams/317726122998",        rowCost: 50 },
  { creator: "Adwuin",              tier: "Silver", followers: 4723,  topPct: 1.89, allTimeAvgCCV: 16.9, langRank: "6478 French",     language: "French",     avgViewers: 15, peakViewers: 18, hours: "6h10",  hoursNum: 6.17,  viewerHours: 92.5,  raisePlatforms: "X / Twitter",         mainQuest: "https://www.twitch.tv/videos/2755781062",                    raiseTheHorn: "https://x.com/Adwuiin/status/2047595871391318037",           skaldHighlight: "",                                                                            meadHallRising: "",   twitchtracker: "https://twitchtracker.com/adwuin/streams/316572637284",         rowCost: 50 },
  { creator: "Lishou",              tier: "Silver", followers: 7132,  topPct: 1.96, allTimeAvgCCV: 37.6, langRank: "6725 French",     language: "French",     avgViewers: 34, peakViewers: 41, hours: "2h",    hoursNum: 2.0,   viewerHours: 68.0,  raisePlatforms: "X / Twitter",         mainQuest: "https://www.twitch.tv/videos/2756696706",                    raiseTheHorn: "https://x.com/Lish2ou/status/2048026078120177791",           skaldHighlight: "https://www.tiktok.com/@lishou.twitch/video/7633378903272295702",            meadHallRising: "",   twitchtracker: "https://twitchtracker.com/lishou/streams/316582307300",         rowCost: 50 },
  { creator: "Eryuyu",              tier: "Silver", followers: 5051,  topPct: 0.85, allTimeAvgCCV: 32.4, langRank: "3178 Spanish",    language: "Spanish",    avgViewers: 28, peakViewers: 33, hours: "3h",    hoursNum: 3.0,   viewerHours: 84.0,  raisePlatforms: "X / Twitter",         mainQuest: "https://www.twitch.tv/eryuyu/v/2757761168",                  raiseTheHorn: "https://x.com/i/status/2048885111228129695",                 skaldHighlight: "https://www.youtube.com/live/rWz3LOYmHl8",                                    meadHallRising: "Yes",twitchtracker: "https://twitchtracker.com/eryuyu/games/25751086",               rowCost: 50 },
  { creator: "IItsTsubaki",         tier: "Bronze", followers: 2033,  topPct: 2.18, allTimeAvgCCV: 12.7, langRank: "7571 Portuguese", language: "Portuguese", avgViewers: 10, peakViewers: 13, hours: "3h03", hoursNum: 3.05,  viewerHours: 30.5,  raisePlatforms: "Instagram",            mainQuest: "https://www.twitch.tv/videos/2761905989",                    raiseTheHorn: "https://www.instagram.com/p/DX1fBM1kdGV/",                  skaldHighlight: "",                                                                            meadHallRising: "",   twitchtracker: "https://twitchtracker.com/itstsubaki/streams/317922108404",     rowCost: 20 },
  { creator: "Hinogashy (1)",       tier: "Silver", followers: 6728,  topPct: 0.52, allTimeAvgCCV: 17.3, langRank: "2050 Portuguese", language: "Portuguese", avgViewers: 26, peakViewers: 29, hours: "2h20",  hoursNum: 2.33,  viewerHours: 60.67, raisePlatforms: "",                     mainQuest: "https://www.twitch.tv/videos/2757629465",                    raiseTheHorn: "",                                                          skaldHighlight: "",                                                                            meadHallRising: "",   twitchtracker: "https://twitchtracker.com/hinogashy/games/25751086",            rowCost: 50 },
  { creator: "Scorphinhooo",        tier: "Silver", followers: 963,   topPct: 0.73, allTimeAvgCCV: 8.8,  langRank: "2938 Portuguese", language: "Portuguese", avgViewers: 15, peakViewers: 25, hours: "18h05", hoursNum: 18.08, viewerHours: 271.25,raisePlatforms: "TikTok",              mainQuest: "https://www.twitch.tv/videos/2760216282",                    raiseTheHorn: "https://www.tiktok.com/@scorpinhoo/video/7634296220638350610", skaldHighlight: "https://www.instagram.com/p/DXuw3nHlBTJ/",                                  meadHallRising: "Yes",twitchtracker: "https://twitchtracker.com/scorpinhoo/games/25751086",           rowCost: 50 },
  { creator: "EUjeffz",             tier: "Bronze", followers: 441,   topPct: 5.06, allTimeAvgCCV: 8.8,  langRank: "15326 Portuguese",language: "Portuguese", avgViewers: 5,  peakViewers: 8,  hours: "1h35",  hoursNum: 1.58,  viewerHours: 7.92,  raisePlatforms: "X / Twitter",         mainQuest: "https://www.twitch.tv/videos/2759488020",                    raiseTheHorn: "https://x.com/eujeffz/status/2049294981626519899",           skaldHighlight: "",                                                                            meadHallRising: "",   twitchtracker: "https://twitchtracker.com/eujeffz/streams/317899367540",        rowCost: 20 },
  { creator: "Weber90",             tier: "Bronze", followers: null,  topPct: null, allTimeAvgCCV: null, langRank: "",                language: "",           avgViewers: 5,  peakViewers: 5,  hours: "15h05", hoursNum: 15.08, viewerHours: 75.42, raisePlatforms: "Threads, X / Twitter",mainQuest: "https://www.twitch.tv/videos/2763440285",                    raiseTheHorn: "https://www.threads.com/@weber._90/post/DXrXutsjKhU",        skaldHighlight: "https://youtube.com/shorts/h8eN54SKZ2U",                                      meadHallRising: "",   twitchtracker: "https://sullygnome.com/channel/weber90/games",                  rowCost: 20 },
  { creator: "IgorBay0",            tier: "Silver", followers: 8064,  topPct: 0.8,  allTimeAvgCCV: 15.6, langRank: "3222 Portuguese", language: "Portuguese", avgViewers: 25, peakViewers: 32, hours: "2h15",  hoursNum: 2.25,  viewerHours: 56.25, raisePlatforms: "YouTube",              mainQuest: "https://www.twitch.tv/videos/2758329486",                    raiseTheHorn: "https://youtube.com/shorts/ajGUjVrsoA0",                    skaldHighlight: "",                                                                            meadHallRising: "",   twitchtracker: "https://twitchtracker.com/igorbay0/streams/317888269428",       rowCost: 50 },
  { creator: "Findseloy",           tier: "Silver", followers: 2463,  topPct: 1.06, allTimeAvgCCV: 18.1, langRank: "4143 Portuguese", language: "Portuguese", avgViewers: 55, peakViewers: 66, hours: "3h15",  hoursNum: 3.25,  viewerHours: 178.75,raisePlatforms: "X / Twitter",         mainQuest: "https://www.twitch.tv/videos/2759492138?t=04h18m35s",        raiseTheHorn: "https://x.com/Findseloy/status/2049766759444480137",         skaldHighlight: "",                                                                            meadHallRising: "",   twitchtracker: "https://twitchtracker.com/findseloy/games/25751086",            rowCost: 50 },
  { creator: "jemplfg",             tier: "Silver", followers: 564,   topPct: 1.8,  allTimeAvgCCV: 20.9, langRank: "55487 English",   language: "English",    avgViewers: 21, peakViewers: 27, hours: "2h54",  hoursNum: 2.9,   viewerHours: 60.9,  raisePlatforms: "X / Twitter",         mainQuest: "https://www.twitch.tv/videos/2763160828",                    raiseTheHorn: "https://x.com/Gjempta_1/status/2050979531817640353",         skaldHighlight: "",                                                                            meadHallRising: "",   twitchtracker: "https://twitchtracker.com/jemplfg/games/25751086",              rowCost: 50 },
  { creator: "Hinogashy (2)",       tier: "Silver", followers: 6728,  topPct: 0.52, allTimeAvgCCV: 17.3, langRank: "2050 Portuguese", language: "Portuguese", avgViewers: 26, peakViewers: 28, hours: "2h20",  hoursNum: 2.33,  viewerHours: 60.67, raisePlatforms: "X / Twitter",         mainQuest: "https://www.twitch.tv/videos/2757629465?t=3h36m35s",         raiseTheHorn: "https://x.com/Hinogashy/status/2048841125587268084",         skaldHighlight: "",                                                                            meadHallRising: "",   twitchtracker: "https://twitchtracker.com/hinogashy/streams/317821876725",      rowCost: 50 },
  { creator: "Imartynfox",          tier: "Silver", followers: 3078,  topPct: 1.65, allTimeAvgCCV: 16.7, langRank: "6036 Portuguese", language: "Portuguese", avgViewers: 27, peakViewers: 32, hours: "2h32",  hoursNum: 2.53,  viewerHours: 68.4,  raisePlatforms: "X / Twitter",         mainQuest: "https://www.twitch.tv/videos/2764276483",                    raiseTheHorn: "https://x.com/iMartynFox/status/2051466061887770670",        skaldHighlight: "https://x.com/iMartynFox/status/2051466061887770670",                         meadHallRising: "",   twitchtracker: "https://twitchtracker.com/imartynfox/streams/317945017972",     rowCost: 50 },
  { creator: "Torynho",             tier: "Silver", followers: 2210,  topPct: 1.49, allTimeAvgCCV: 13.6, langRank: "5487 Portuguese", language: "Portuguese", avgViewers: 19, peakViewers: 21, hours: "2h30",  hoursNum: 2.5,   viewerHours: 47.5,  raisePlatforms: "YouTube",              mainQuest: "https://www.twitch.tv/videos/2771973837",                    raiseTheHorn: "https://youtube.com/shorts/b4KrXXlDDrs",                    skaldHighlight: "",                                                                            meadHallRising: "",   twitchtracker: "https://twitchtracker.com/torynho/streams/318019987572",        rowCost: 50 },
];
