// Generated from gridbeat_kpi_report_v3.html on 16 Sep 2026. 48 accepted creator rows,
// 46 marked Done and 2 Open. Steam key codes from the source sheet are deliberately not included.
// hours are formatted from the logged decimal value; viewerHours as logged in the sheet.
export type GbRow = {
  creator: string;
  status: "Done" | "Open";
  tier: "Silver" | "Bronze";
  language: string;
  followers: number;
  /** TwitchTracker global top percentage at screening. */
  topPct: number | null;
  /** TwitchTracker rank within the creator language. */
  langRank: number | null;
  /** Historic average viewers at screening. */
  histAvg: number;
  avgViewers: number;
  peakViewers: number;
  hours: string;
  hoursNum: number;
  viewerHours: number;
  demoVod: string;
  launchVod: string;
  signalBoost: string;
  linkSyncProofs: string[];
  launchSupportProofs: string[];
  bonusPosts: string[];
  tracker: string;
  didDemo: boolean;
  didLaunch: boolean;
  hasSignalBoost: boolean;
  hasLinkSync: boolean;
  hasLaunchSupport: boolean;
  socialTouchpoints: number;
  largeProfile: boolean;
};

export const rows: GbRow[] = [
  {"creator":"FabetaGames","status":"Done","tier":"Silver","language":"Portuguese","followers":706,"topPct":1.74,"langRank":6607,"histAvg":24,"avgViewers":38,"peakViewers":52,"hours":"2h07","hoursNum":2.117,"viewerHours":80.4,"demoVod":"https://www.twitch.tv/videos/2734086930","launchVod":"https://www.twitch.tv/videos/2734184364","signalBoost":"https://www.tiktok.com/@fabetagames/video/7622681338398690580","linkSyncProofs":[],"launchSupportProofs":[],"bonusPosts":[],"tracker":"https://twitchtracker.com/fabetagames/games/541516517","didDemo":true,"didLaunch":true,"hasSignalBoost":true,"hasLinkSync":true,"hasLaunchSupport":true,"socialTouchpoints":3,"largeProfile":false},
  {"creator":"Undoubtedlylink","status":"Done","tier":"Silver","language":"English","followers":2224,"topPct":0.79,"langRank":24663,"histAvg":43,"avgViewers":36,"peakViewers":39,"hours":"2h20","hoursNum":2.333,"viewerHours":84,"demoVod":"https://www.twitch.tv/videos/2733186261","launchVod":"https://www.twitch.tv/videos/2729140151","signalBoost":"https://x.com/UndoubtedlyLink/status/2037621072225247251","linkSyncProofs":[],"launchSupportProofs":[],"bonusPosts":[],"tracker":"https://twitchtracker.com/undoubtedlylink/games/541516517","didDemo":true,"didLaunch":true,"hasSignalBoost":true,"hasLinkSync":true,"hasLaunchSupport":true,"socialTouchpoints":3,"largeProfile":false},
  {"creator":"QueenJeey","status":"Done","tier":"Silver","language":"Portuguese","followers":1317,"topPct":1.67,"langRank":6407,"histAvg":15,"avgViewers":15,"peakViewers":22,"hours":"2h30","hoursNum":2.5,"viewerHours":37.5,"demoVod":"https://www.twitch.tv/videos/2728018128?t=04h03m06s","launchVod":"https://www.twitch.tv/videos/2733077605?t=02h31m48s","signalBoost":"https://www.tiktok.com/@twtv.queenjeey/video/7622313739550723349","linkSyncProofs":[],"launchSupportProofs":[],"bonusPosts":[],"tracker":"https://twitchtracker.com/queenjeey/games/541516517","didDemo":true,"didLaunch":true,"hasSignalBoost":true,"hasLinkSync":true,"hasLaunchSupport":true,"socialTouchpoints":3,"largeProfile":false},
  {"creator":"LunariValkyrie","status":"Done","tier":"Silver","language":"English","followers":16205,"topPct":0.91,"langRank":28504,"histAvg":19,"avgViewers":22,"peakViewers":27,"hours":"2h50","hoursNum":2.833,"viewerHours":62.3,"demoVod":"https://www.twitch.tv/videos/2728685490?t=03h24m10s","launchVod":"https://www.twitch.tv/videos/2731987557?t=08h03m01s","signalBoost":"https://www.tiktok.com/@lunarivalkyrie/video/7620003746784840974","linkSyncProofs":[],"launchSupportProofs":[],"bonusPosts":[],"tracker":"https://twitchtracker.com/lunarivalkyrie/games/541516517","didDemo":true,"didLaunch":true,"hasSignalBoost":true,"hasLinkSync":true,"hasLaunchSupport":true,"socialTouchpoints":3,"largeProfile":true},
  {"creator":"Paildry","status":"Done","tier":"Silver","language":"German","followers":795,"topPct":1.34,"langRank":6398,"histAvg":20,"avgViewers":18,"peakViewers":21,"hours":"2h10","hoursNum":2.167,"viewerHours":39,"demoVod":"https://www.twitch.tv/videos/2729144187","launchVod":"https://www.twitch.tv/videos/2732172756","signalBoost":"https://x.com/Paildry/status/2037240875512635674","linkSyncProofs":[],"launchSupportProofs":[],"bonusPosts":[],"tracker":"https://twitchtracker.com/paildry/games/541516517","didDemo":true,"didLaunch":true,"hasSignalBoost":true,"hasLinkSync":true,"hasLaunchSupport":true,"socialTouchpoints":3,"largeProfile":false},
  {"creator":"Paschoalin","status":"Done","tier":"Silver","language":"Portuguese","followers":4774,"topPct":1.3,"langRank":5112,"histAvg":15,"avgViewers":16,"peakViewers":21,"hours":"2h30","hoursNum":2.5,"viewerHours":40,"demoVod":"https://www.twitch.tv/videos/2732525220?t=00h08m08s","launchVod":"https://www.twitch.tv/videos/2727260801?t=01h14m35s","signalBoost":"","linkSyncProofs":[],"launchSupportProofs":[],"bonusPosts":[],"tracker":"https://twitchtracker.com/paschoalin/streams/317583323893","didDemo":true,"didLaunch":true,"hasSignalBoost":false,"hasLinkSync":false,"hasLaunchSupport":true,"socialTouchpoints":1,"largeProfile":false},
  {"creator":"HaouAnubis","status":"Done","tier":"Silver","language":"English","followers":541,"topPct":1.21,"langRank":38752,"histAvg":34,"avgViewers":39,"peakViewers":60,"hours":"2h25","hoursNum":2.417,"viewerHours":94.2,"demoVod":"https://www.twitch.tv/videos/2733246887","launchVod":"https://www.twitch.tv/videos/2730544771","signalBoost":"","linkSyncProofs":["https://x.com/PharaohAnubis/status/2037643456302969262"],"launchSupportProofs":[],"bonusPosts":[],"tracker":"https://twitchtracker.com/haouanubis/games/541516517","didDemo":true,"didLaunch":true,"hasSignalBoost":false,"hasLinkSync":true,"hasLaunchSupport":true,"socialTouchpoints":2,"largeProfile":false},
  {"creator":"ItsTsubaki","status":"Done","tier":"Bronze","language":"Portuguese","followers":2032,"topPct":2.96,"langRank":10142,"histAvg":10,"avgViewers":9,"peakViewers":10,"hours":"1h00","hoursNum":1,"viewerHours":9,"demoVod":"https://www.twitch.tv/videos/2728316078?t=0h0m1s","launchVod":"","signalBoost":"https://youtu.be/TgWGaOnopX8","linkSyncProofs":[],"launchSupportProofs":[],"bonusPosts":[],"tracker":"https://twitchtracker.com/itstsubaki/games/541516517","didDemo":true,"didLaunch":false,"hasSignalBoost":true,"hasLinkSync":true,"hasLaunchSupport":false,"socialTouchpoints":2,"largeProfile":false},
  {"creator":"Beacan_","status":"Done","tier":"Silver","language":"English","followers":758,"topPct":2.67,"langRank":91152,"histAvg":12,"avgViewers":15,"peakViewers":25,"hours":"3h15","hoursNum":3.25,"viewerHours":48.8,"demoVod":"https://www.twitch.tv/videos/2725587558","launchVod":"https://www.twitch.tv/videos/2732278017","signalBoost":"","linkSyncProofs":[],"launchSupportProofs":[],"bonusPosts":[],"tracker":"https://twitchtracker.com/beacan_/streams/315677464532","didDemo":true,"didLaunch":true,"hasSignalBoost":false,"hasLinkSync":false,"hasLaunchSupport":true,"socialTouchpoints":1,"largeProfile":false},
  {"creator":"Ryplai","status":"Done","tier":"Silver","language":"Portuguese","followers":1485,"topPct":0.59,"langRank":2489,"histAvg":32,"avgViewers":40,"peakViewers":42,"hours":"1h42","hoursNum":1.7,"viewerHours":68,"demoVod":"https://www.twitch.tv/videos/2733164126?t=0h0m1s","launchVod":"","signalBoost":"","linkSyncProofs":[],"launchSupportProofs":[],"bonusPosts":[],"tracker":"https://twitchtracker.com/ryplai/streams/317647912308","didDemo":true,"didLaunch":false,"hasSignalBoost":false,"hasLinkSync":true,"hasLaunchSupport":true,"socialTouchpoints":2,"largeProfile":false},
  {"creator":"Genkaku","status":"Done","tier":"Silver","language":"Portuguese","followers":36028,"topPct":0.72,"langRank":2987,"histAvg":60,"avgViewers":66,"peakViewers":75,"hours":"2h10","hoursNum":2.167,"viewerHours":143,"demoVod":"https://www.twitch.tv/videos/2725751604","launchVod":"https://www.twitch.tv/videos/2732661418","signalBoost":"https://x.com/NWGamesBrasil/status/2037336479429501130","linkSyncProofs":[],"launchSupportProofs":[],"bonusPosts":[],"tracker":"https://twitchtracker.com/genkaku/games/541516517","didDemo":true,"didLaunch":true,"hasSignalBoost":true,"hasLinkSync":false,"hasLaunchSupport":true,"socialTouchpoints":2,"largeProfile":true},
  {"creator":"Torynho","status":"Done","tier":"Silver","language":"Portuguese","followers":2275,"topPct":1.14,"langRank":4542,"histAvg":12,"avgViewers":14,"peakViewers":23,"hours":"2h10","hoursNum":2.167,"viewerHours":30.3,"demoVod":"","launchVod":"https://www.twitch.tv/videos/2733476034","signalBoost":"https://www.youtube.com/shorts/9-CsnndEMcg","linkSyncProofs":[],"launchSupportProofs":[],"bonusPosts":[],"tracker":"https://twitchtracker.com/torynho/games/541516517","didDemo":false,"didLaunch":true,"hasSignalBoost":true,"hasLinkSync":false,"hasLaunchSupport":true,"socialTouchpoints":2,"largeProfile":false},
  {"creator":"Nandoida","status":"Done","tier":"Silver","language":"Portuguese","followers":5125,"topPct":0.28,"langRank":1223,"histAvg":113,"avgViewers":51,"peakViewers":63,"hours":"2h30","hoursNum":2.5,"viewerHours":127.5,"demoVod":"https://www.twitch.tv/videos/2733162605?t=03h43m39s","launchVod":"https://www.twitch.tv/videos/2726486765?t=04h34m46s","signalBoost":"","linkSyncProofs":[],"launchSupportProofs":[],"bonusPosts":[],"tracker":"https://twitchtracker.com/nandoida/games/541516517","didDemo":true,"didLaunch":true,"hasSignalBoost":true,"hasLinkSync":false,"hasLaunchSupport":true,"socialTouchpoints":2,"largeProfile":false},
  {"creator":"Findseloy","status":"Done","tier":"Silver","language":"Portuguese","followers":2437,"topPct":1.58,"langRank":6072,"histAvg":14,"avgViewers":22,"peakViewers":32,"hours":"2h10","hoursNum":2.167,"viewerHours":47.7,"demoVod":"https://www.twitch.tv/videos/2732563839?t=04h43m38s","launchVod":"https://www.twitch.tv/videos/2726940485","signalBoost":"https://youtube.com/shorts/pZckQRJ4vds","linkSyncProofs":[],"launchSupportProofs":[],"bonusPosts":[],"tracker":"https://twitchtracker.com/findseloy/games/541516517","didDemo":true,"didLaunch":true,"hasSignalBoost":true,"hasLinkSync":true,"hasLaunchSupport":true,"socialTouchpoints":3,"largeProfile":false},
  {"creator":"Silent _genius","status":"Done","tier":"Bronze","language":"French","followers":229,"topPct":4.64,"langRank":17565,"histAvg":8,"avgViewers":5,"peakViewers":5,"hours":"1h45","hoursNum":1.75,"viewerHours":8.8,"demoVod":"","launchVod":"https://www.twitch.tv/videos/2732400811","signalBoost":"","linkSyncProofs":[],"launchSupportProofs":[],"bonusPosts":[],"tracker":"https://twitchtracker.com/silent_genius/streams/316340043491","didDemo":false,"didLaunch":true,"hasSignalBoost":false,"hasLinkSync":false,"hasLaunchSupport":true,"socialTouchpoints":1,"largeProfile":false},
  {"creator":"TattyHikari","status":"Done","tier":"Silver","language":"Portuguese","followers":4890,"topPct":0.81,"langRank":3326,"histAvg":35,"avgViewers":26,"peakViewers":32,"hours":"2h35","hoursNum":2.583,"viewerHours":67.2,"demoVod":"","launchVod":"https://www.twitch.tv/videos/2732689112","signalBoost":"https://www.tiktok.com/@tattyhikari/video/7621863622674795797","linkSyncProofs":[],"launchSupportProofs":[],"bonusPosts":[],"tracker":"https://twitchtracker.com/tattyhikari/games/541516517","didDemo":false,"didLaunch":true,"hasSignalBoost":true,"hasLinkSync":true,"hasLaunchSupport":true,"socialTouchpoints":3,"largeProfile":false},
  {"creator":"Scorphinoo","status":"Done","tier":"Silver","language":"Portuguese","followers":936,"topPct":1.03,"langRank":4131,"histAvg":11,"avgViewers":19,"peakViewers":22,"hours":"3h30","hoursNum":3.5,"viewerHours":66.5,"demoVod":"https://www.twitch.tv/videos/2728834491","launchVod":"https://www.twitch.tv/videos/2732414840","signalBoost":"","linkSyncProofs":[],"launchSupportProofs":["https://www.youtube.com/watch?v=IMwkM8k03CU%20https://www.instagram.com/reels/DWY17LTj7Sv/%20https://www.tiktok.com/@scorpinhoo/video/7621913644682448144"],"bonusPosts":["https://www.tiktok.com/@scorpinhoo/video/7621913644682448144","https://www.instagram.com/reels/DWY17LTj7S"],"tracker":"https://twitchtracker.com/scorpinhoo","didDemo":true,"didLaunch":true,"hasSignalBoost":false,"hasLinkSync":false,"hasLaunchSupport":true,"socialTouchpoints":2,"largeProfile":false},
  {"creator":"Maveco","status":"Done","tier":"Silver","language":"Portuguese","followers":12081,"topPct":1.15,"langRank":4575,"histAvg":19,"avgViewers":20,"peakViewers":24,"hours":"3h20","hoursNum":3.333,"viewerHours":66.7,"demoVod":"https://www.twitch.tv/videos/2730533845?t=2h47m44s","launchVod":"https://www.twitch.tv/videos/2732965311?t=2h54m11s","signalBoost":"","linkSyncProofs":[],"launchSupportProofs":[],"bonusPosts":[],"tracker":"https://twitchtracker.com/maveco/games/541516517","didDemo":true,"didLaunch":true,"hasSignalBoost":true,"hasLinkSync":false,"hasLaunchSupport":true,"socialTouchpoints":2,"largeProfile":true},
  {"creator":"Hinogashy","status":"Done","tier":"Silver","language":"Portuguese","followers":6717,"topPct":1.09,"langRank":4331,"histAvg":14,"avgViewers":15,"peakViewers":21,"hours":"2h30","hoursNum":2.5,"viewerHours":37.5,"demoVod":"https://www.twitch.tv/videos/2730703711?t=7h24m44s","launchVod":"https://www.twitch.tv/videos/2733896068?t=10h33m23s","signalBoost":"https://x.com/Hinogashy/status/2038143728255209779","linkSyncProofs":[],"launchSupportProofs":[],"bonusPosts":[],"tracker":"https://twitchtracker.com/hinogashy/games/541516517","didDemo":true,"didLaunch":true,"hasSignalBoost":true,"hasLinkSync":false,"hasLaunchSupport":true,"socialTouchpoints":2,"largeProfile":false},
  {"creator":"Foythtv","status":"Done","tier":"Silver","language":"Portuguese","followers":9721,"topPct":0.35,"langRank":1543,"histAvg":78,"avgViewers":44,"peakViewers":60,"hours":"2h05","hoursNum":2.083,"viewerHours":91.7,"demoVod":"","launchVod":"https://www.twitch.tv/videos/2732201305","signalBoost":"","linkSyncProofs":[],"launchSupportProofs":[],"bonusPosts":[],"tracker":"https://twitchtracker.com/foythtv/games/541516517","didDemo":false,"didLaunch":true,"hasSignalBoost":false,"hasLinkSync":true,"hasLaunchSupport":true,"socialTouchpoints":2,"largeProfile":false},
  {"creator":"EuJeffz","status":"Done","tier":"Bronze","language":"Portuguese","followers":430,"topPct":3.4,"langRank":11290,"histAvg":10,"avgViewers":9,"peakViewers":10,"hours":"2h00","hoursNum":2,"viewerHours":18,"demoVod":"https://www.twitch.tv/videos/2732502981","launchVod":"https://www.twitch.tv/videos/2729167841","signalBoost":"","linkSyncProofs":[],"launchSupportProofs":[],"bonusPosts":[],"tracker":"https://twitchtracker.com/eujeffz/games/541516517","didDemo":true,"didLaunch":true,"hasSignalBoost":true,"hasLinkSync":false,"hasLaunchSupport":false,"socialTouchpoints":1,"largeProfile":false},
  {"creator":"lariex","status":"Done","tier":"Bronze","language":"Portuguese","followers":4366,"topPct":1.24,"langRank":4918,"histAvg":26,"avgViewers":11,"peakViewers":13,"hours":"1h05","hoursNum":1.083,"viewerHours":11.9,"demoVod":"https://www.twitch.tv/videos/2728169492","launchVod":"","signalBoost":"https://x.com/_Lariex/status/2035401806793089053","linkSyncProofs":[],"launchSupportProofs":[],"bonusPosts":[],"tracker":"https://twitchtracker.com/lariex/games/541516517","didDemo":true,"didLaunch":false,"hasSignalBoost":true,"hasLinkSync":false,"hasLaunchSupport":false,"socialTouchpoints":1,"largeProfile":false},
  {"creator":"Labsy","status":"Done","tier":"Bronze","language":"French","followers":666,"topPct":3.76,"langRank":14023,"histAvg":9.3,"avgViewers":4,"peakViewers":5,"hours":"2h38","hoursNum":2.633,"viewerHours":10.5,"demoVod":"https://www.twitch.tv/videos/2735431116","launchVod":"","signalBoost":"https://www.tiktok.com/@labsytv","linkSyncProofs":[],"launchSupportProofs":[],"bonusPosts":["https://youtube.com/shorts/OMkGvhVE6n0"],"tracker":"https://sullygnome.com/channel/labsy/stream/316352876388","didDemo":true,"didLaunch":false,"hasSignalBoost":true,"hasLinkSync":true,"hasLaunchSupport":false,"socialTouchpoints":3,"largeProfile":false},
  {"creator":"Lordacris Plays","status":"Done","tier":"Silver","language":"English","followers":1048,"topPct":0.82,"langRank":25536,"histAvg":22,"avgViewers":23,"peakViewers":29,"hours":"2h10","hoursNum":2.167,"viewerHours":49.8,"demoVod":"https://www.twitch.tv/videos/2733170418?t=3h30m39s","launchVod":"https://www.twitch.tv/videos/2728055265?t=2h0m9s","signalBoost":"","linkSyncProofs":[],"launchSupportProofs":[],"bonusPosts":[],"tracker":"https://twitchtracker.com/lordacrisplays/streams/315382418770","didDemo":true,"didLaunch":true,"hasSignalBoost":false,"hasLinkSync":false,"hasLaunchSupport":true,"socialTouchpoints":1,"largeProfile":false},
  {"creator":"Savage_Kai","status":"Done","tier":"Bronze","language":"English","followers":1519,"topPct":2.53,"langRank":86034,"histAvg":13,"avgViewers":10,"peakViewers":12,"hours":"3h13","hoursNum":3.217,"viewerHours":32.2,"demoVod":"https://www.twitch.tv/videos/2732359749","launchVod":"https://www.twitch.tv/videos/2729892662","signalBoost":"","linkSyncProofs":["https://www.instagram.com/stories/kylabooysen/3861526944139719373?utm_source=ig_story_item_share&igsh=eHdnNTlncmZnazA3"],"launchSupportProofs":[],"bonusPosts":[],"tracker":"https://twitchtracker.com/savage_kai/games/541516517","didDemo":true,"didLaunch":true,"hasSignalBoost":true,"hasLinkSync":true,"hasLaunchSupport":true,"socialTouchpoints":3,"largeProfile":false},
  {"creator":"Ellandria","status":"Done","tier":"Silver","language":"Portuguese","followers":7408,"topPct":0.39,"langRank":1680,"histAvg":61,"avgViewers":56,"peakViewers":66,"hours":"2h15","hoursNum":2.25,"viewerHours":126,"demoVod":"","launchVod":"https://www.twitch.tv/videos/2732185242?t=2h29m43s","signalBoost":"https://x.com/elllandria/status/2037239249389465965","linkSyncProofs":[],"launchSupportProofs":[],"bonusPosts":[],"tracker":"https://twitchtracker.com/elllandria/games/541516517","didDemo":false,"didLaunch":true,"hasSignalBoost":true,"hasLinkSync":true,"hasLaunchSupport":true,"socialTouchpoints":3,"largeProfile":false},
  {"creator":"Imartynfox","status":"Done","tier":"Silver","language":"Portuguese","followers":3388,"topPct":1.03,"langRank":4143,"histAvg":30,"avgViewers":15,"peakViewers":21,"hours":"2h30","hoursNum":2.5,"viewerHours":37.5,"demoVod":"https://www.twitch.tv/videos/2732497492","launchVod":"https://www.twitch.tv/videos/2726629683","signalBoost":"https://x.com/iMartynFox/status/2037329720862224748?s=20","linkSyncProofs":["https://x.com/iMartynFox/status/2037329720862224748?s=20"],"launchSupportProofs":[],"bonusPosts":[],"tracker":"https://twitchtracker.com/imartynfox/games/541516517","didDemo":true,"didLaunch":true,"hasSignalBoost":true,"hasLinkSync":true,"hasLaunchSupport":true,"socialTouchpoints":3,"largeProfile":false},
  {"creator":"Sbuddypoke","status":"Done","tier":"Silver","language":"Portuguese","followers":4776,"topPct":1.17,"langRank":4675,"histAvg":17,"avgViewers":15,"peakViewers":19,"hours":"2h37","hoursNum":2.617,"viewerHours":39.2,"demoVod":"","launchVod":"https://www.twitch.tv/videos/2735074129?t=0h0m1s","signalBoost":"","linkSyncProofs":[],"launchSupportProofs":[],"bonusPosts":[],"tracker":"https://twitchtracker.com/sbuddypoke/games/541516517","didDemo":false,"didLaunch":true,"hasSignalBoost":false,"hasLinkSync":true,"hasLaunchSupport":false,"socialTouchpoints":1,"largeProfile":false},
  {"creator":"John_Shinoda","status":"Done","tier":"Bronze","language":"Portuguese","followers":6755,"topPct":0.41,"langRank":1757,"histAvg":72,"avgViewers":5,"peakViewers":5,"hours":"1h10","hoursNum":1.167,"viewerHours":5.8,"demoVod":"https://www.twitch.tv/videos/2733461560","launchVod":"","signalBoost":"","linkSyncProofs":["https://www.instagram.com/p/DWarA7jCcho/"],"launchSupportProofs":[],"bonusPosts":["https://www.tiktok.com/@jksjohnshinoda/video/7622179427388116225","https://www.youtube.com/shorts/XNgH_73g4nc"],"tracker":"https://twitchtracker.com/cosminhas2/streams/317516790774","didDemo":true,"didLaunch":false,"hasSignalBoost":false,"hasLinkSync":true,"hasLaunchSupport":true,"socialTouchpoints":3,"largeProfile":false},
  {"creator":"CosminhaS2","status":"Done","tier":"Silver","language":"Portuguese","followers":6755,"topPct":0.41,"langRank":1757,"histAvg":72,"avgViewers":35,"peakViewers":39,"hours":"2h31","hoursNum":2.517,"viewerHours":88.1,"demoVod":"","launchVod":"https://www.twitch.tv/videos/2733260925","signalBoost":"https://x.com/CosminhaS2/status/2037660230897557792","linkSyncProofs":[],"launchSupportProofs":[],"bonusPosts":[],"tracker":"https://twitchtracker.com/cosminhas2/streams/317516790774","didDemo":false,"didLaunch":true,"hasSignalBoost":true,"hasLinkSync":true,"hasLaunchSupport":true,"socialTouchpoints":3,"largeProfile":false},
  {"creator":"EnGuyTV","status":"Open","tier":"Silver","language":"French","followers":1270,"topPct":1.8,"langRank":6623,"histAvg":12,"avgViewers":15,"peakViewers":20,"hours":"2h10","hoursNum":2.167,"viewerHours":32.5,"demoVod":"https://www.twitch.tv/videos/2726352758","launchVod":"https://www.twitch.tv/videos/2733858396","signalBoost":"https://www.youtube.com/shorts/_66x0IPnHFI","linkSyncProofs":[],"launchSupportProofs":[],"bonusPosts":["https://www.youtube.com/shorts/2D3-kWeaLkE","https://www.youtube.com/shorts/s56pSXoLCYg"],"tracker":"https://twitchtracker.com/enguytv/games/541516517","didDemo":true,"didLaunch":true,"hasSignalBoost":true,"hasLinkSync":true,"hasLaunchSupport":true,"socialTouchpoints":4,"largeProfile":false},
  {"creator":"Kiuzinho","status":"Done","tier":"Bronze","language":"English","followers":26195,"topPct":0.77,"langRank":24023,"histAvg":27,"avgViewers":10,"peakViewers":12,"hours":"1h05","hoursNum":1.083,"viewerHours":10.8,"demoVod":"","launchVod":"","signalBoost":"","linkSyncProofs":[],"launchSupportProofs":[],"bonusPosts":[],"tracker":"https://twitchtracker.com/kiuzinho/games/541516517","didDemo":false,"didLaunch":false,"hasSignalBoost":true,"hasLinkSync":false,"hasLaunchSupport":true,"socialTouchpoints":2,"largeProfile":true},
  {"creator":"eyklor","status":"Done","tier":"Bronze","language":"French","followers":476,"topPct":1.47,"langRank":5409,"histAvg":17,"avgViewers":12,"peakViewers":19,"hours":"1h20","hoursNum":1.333,"viewerHours":16,"demoVod":"https://www.twitch.tv/videos/2726329748","launchVod":"","signalBoost":"","linkSyncProofs":[],"launchSupportProofs":[],"bonusPosts":[],"tracker":"https://twitchtracker.com/eyklor/streams/316276403939","didDemo":true,"didLaunch":false,"hasSignalBoost":true,"hasLinkSync":false,"hasLaunchSupport":true,"socialTouchpoints":2,"largeProfile":false},
  {"creator":"Mafraju","status":"Done","tier":"Bronze","language":"Portuguese","followers":10507,"topPct":1.84,"langRank":6951,"histAvg":13,"avgViewers":12,"peakViewers":14,"hours":"2h10","hoursNum":2.167,"viewerHours":26,"demoVod":"https://www.twitch.tv/videos/2733808252","launchVod":"https://www.twitch.tv/videos/2733808252","signalBoost":"","linkSyncProofs":[],"launchSupportProofs":[],"bonusPosts":[],"tracker":"https://twitchtracker.com/mafraju/games/541516517","didDemo":true,"didLaunch":true,"hasSignalBoost":true,"hasLinkSync":false,"hasLaunchSupport":true,"socialTouchpoints":2,"largeProfile":true},
  {"creator":"igorbayo","status":"Done","tier":"Silver","language":"Portuguese","followers":8043,"topPct":1.3,"langRank":5138,"histAvg":15,"avgViewers":15,"peakViewers":15,"hours":"1h30","hoursNum":1.5,"viewerHours":22.5,"demoVod":"","launchVod":"https://www.twitch.tv/videos/2732924139","signalBoost":"https://youtube.com/shorts/lESv8x10plE?feature=share","linkSyncProofs":[],"launchSupportProofs":[],"bonusPosts":[],"tracker":"https://twitchtracker.com/igorbay0/games/541516517","didDemo":false,"didLaunch":true,"hasSignalBoost":true,"hasLinkSync":false,"hasLaunchSupport":false,"socialTouchpoints":1,"largeProfile":false},
  {"creator":"Peardoll","status":"Done","tier":"Silver","language":"English","followers":1392,"topPct":2.91,"langRank":99815,"histAvg":13,"avgViewers":22,"peakViewers":27,"hours":"2h20","hoursNum":2.333,"viewerHours":51.3,"demoVod":"https://www.twitch.tv/videos/2727624925?t=01h05m23s","launchVod":"https://www.twitch.tv/videos/2732531919?t=00h05m46s","signalBoost":"","linkSyncProofs":[],"launchSupportProofs":[],"bonusPosts":[],"tracker":"https://twitchtracker.com/peardoll/games/541516517","didDemo":true,"didLaunch":true,"hasSignalBoost":false,"hasLinkSync":false,"hasLaunchSupport":true,"socialTouchpoints":1,"largeProfile":false},
  {"creator":"Phenexa","status":"Done","tier":"Silver","language":"English","followers":3552,"topPct":1.17,"langRank":37314,"histAvg":22,"avgViewers":21,"peakViewers":26,"hours":"2h30","hoursNum":2.5,"viewerHours":52.5,"demoVod":"https://www.twitch.tv/videos/2728317996?t=02h09m48s","launchVod":"https://www.twitch.tv/videos/2732431765?t=02h06m45s","signalBoost":"https://youtube.com/shorts/aD7JPyz44fA?feature=share","linkSyncProofs":[],"launchSupportProofs":[],"bonusPosts":[],"tracker":"https://twitchtracker.com/phenexa/games/541516517","didDemo":true,"didLaunch":true,"hasSignalBoost":true,"hasLinkSync":true,"hasLaunchSupport":true,"socialTouchpoints":3,"largeProfile":false},
  {"creator":"Mishoots","status":"Done","tier":"Silver","language":"German","followers":577,"topPct":0.71,"langRank":3410,"histAvg":30,"avgViewers":29,"peakViewers":34,"hours":"1h10","hoursNum":1.167,"viewerHours":33.8,"demoVod":"","launchVod":"https://www.twitch.tv/videos/2732918631?t=4h12m50s","signalBoost":"https://www.tiktok.com/@mishoots_gaming/video/7622049109356121376","linkSyncProofs":[],"launchSupportProofs":[],"bonusPosts":[],"tracker":"https://twitchtracker.com/mishoots/games/541516517","didDemo":false,"didLaunch":true,"hasSignalBoost":true,"hasLinkSync":false,"hasLaunchSupport":true,"socialTouchpoints":2,"largeProfile":false},
  {"creator":"Fradda","status":"Done","tier":"Bronze","language":"English","followers":870,"topPct":4.19,"langRank":147194,"histAvg":6,"avgViewers":8,"peakViewers":9,"hours":"1h20","hoursNum":1.333,"viewerHours":10.7,"demoVod":"","launchVod":"https://www.twitch.tv/videos/2736102906","signalBoost":"","linkSyncProofs":[],"launchSupportProofs":[],"bonusPosts":[],"tracker":"https://twitchtracker.com/fradda/games/541516517","didDemo":false,"didLaunch":true,"hasSignalBoost":false,"hasLinkSync":true,"hasLaunchSupport":false,"socialTouchpoints":1,"largeProfile":false},
  {"creator":"Sirzoidberg13","status":"Done","tier":"Bronze","language":"English","followers":300,"topPct":4.87,"langRank":183194,"histAvg":5,"avgViewers":4,"peakViewers":5,"hours":"1h20","hoursNum":1.333,"viewerHours":5.3,"demoVod":"https://www.twitch.tv/videos/2731016710","launchVod":"","signalBoost":"","linkSyncProofs":[],"launchSupportProofs":[],"bonusPosts":[],"tracker":"https://sullygnome.com/channel/sirzoidberg13/stream/317190386263","didDemo":true,"didLaunch":false,"hasSignalBoost":true,"hasLinkSync":false,"hasLaunchSupport":false,"socialTouchpoints":1,"largeProfile":false},
  {"creator":"Shalalaka","status":"Done","tier":"Silver","language":"Portuguese","followers":14145,"topPct":0.35,"langRank":1530,"histAvg":43,"avgViewers":51,"peakViewers":71,"hours":"2h10","hoursNum":2.167,"viewerHours":110.5,"demoVod":"","launchVod":"https://www.twitch.tv/videos/2732502479?t=02h12m21s","signalBoost":"https://www.tiktok.com/@shalalakacidade/video/7621888547334786324","linkSyncProofs":[],"launchSupportProofs":[],"bonusPosts":[],"tracker":"https://twitchtracker.com/shalalaka/games/541516517","didDemo":false,"didLaunch":true,"hasSignalBoost":true,"hasLinkSync":true,"hasLaunchSupport":true,"socialTouchpoints":3,"largeProfile":true},
  {"creator":"UmbritaC","status":"Open","tier":"Silver","language":"Romanian","followers":2753,"topPct":1.95,"langRank":99,"histAvg":15,"avgViewers":17,"peakViewers":22,"hours":"2h05","hoursNum":2.083,"viewerHours":35.4,"demoVod":"http://twitch.tv/videos/2732233832?t=2h12m52s","launchVod":"https://www.twitch.tv/videos/2730701651?t=1h35m10s","signalBoost":"","linkSyncProofs":["https://x.com/UmbritaC/status/2035386726118523155"],"launchSupportProofs":[],"bonusPosts":[],"tracker":"https://twitchtracker.com/umbritac/games/541516517","didDemo":true,"didLaunch":true,"hasSignalBoost":true,"hasLinkSync":true,"hasLaunchSupport":true,"socialTouchpoints":3,"largeProfile":false},
  {"creator":"GirlWhoPlays","status":"Done","tier":"Silver","language":"Spanish","followers":4724,"topPct":0.54,"langRank":2255,"histAvg":51,"avgViewers":45,"peakViewers":52,"hours":"1h50","hoursNum":1.833,"viewerHours":82.5,"demoVod":"https://www.twitch.tv/videos/2731845228?t=00h03m09s","launchVod":"","signalBoost":"","linkSyncProofs":[],"launchSupportProofs":[],"bonusPosts":[],"tracker":"https://twitchtracker.com/girlwhoplays/games/541516517","didDemo":true,"didLaunch":false,"hasSignalBoost":true,"hasLinkSync":false,"hasLaunchSupport":false,"socialTouchpoints":1,"largeProfile":false},
  {"creator":"ARTTT","status":"Done","tier":"Bronze","language":"Portuguese","followers":1371,"topPct":0.32,"langRank":1371,"histAvg":35.5,"avgViewers":5,"peakViewers":5,"hours":"1h30","hoursNum":1.5,"viewerHours":7.5,"demoVod":"https://www.twitch.tv/videos/2731779475?filter=archives&sort=time","launchVod":"https://www.twitch.tv/videos/2731748116?filter=archives&sort=time","signalBoost":"https://vt.tiktok.com/ZSuT4PLQb/","linkSyncProofs":[],"launchSupportProofs":[],"bonusPosts":[],"tracker":"https://sullygnome.com/channel/arttt","didDemo":true,"didLaunch":true,"hasSignalBoost":true,"hasLinkSync":true,"hasLaunchSupport":false,"socialTouchpoints":2,"largeProfile":false},
  {"creator":"Rhariane","status":"Done","tier":"Silver","language":"Portuguese","followers":5487,"topPct":0.45,"langRank":1940,"histAvg":67,"avgViewers":66,"peakViewers":84,"hours":"4h30","hoursNum":4.5,"viewerHours":297,"demoVod":"https://www.twitch.tv/videos/2732776137?t=02h48m52s","launchVod":"https://www.twitch.tv/videos/2732776137?t=02h51m16s","signalBoost":"","linkSyncProofs":[],"launchSupportProofs":[],"bonusPosts":[],"tracker":"https://twitchtracker.com/rhariane/games/541516517","didDemo":true,"didLaunch":true,"hasSignalBoost":true,"hasLinkSync":true,"hasLaunchSupport":false,"socialTouchpoints":2,"largeProfile":false},
  {"creator":"Schrodinerkitten","status":"Done","tier":"Silver","language":"French","followers":2487,"topPct":1.86,"langRank":6855,"histAvg":14,"avgViewers":17,"peakViewers":23,"hours":"5h20","hoursNum":5.333,"viewerHours":90.7,"demoVod":"https://www.twitch.tv/videos/2729954667?t=0h11m55s","launchVod":"https://www.twitch.tv/videos/2732364468?t=0h10m39s","signalBoost":"https://bsky.app/profile/schrodingerkitten.bsky.social/post/3mhyajiilnk2r","linkSyncProofs":[],"launchSupportProofs":[],"bonusPosts":[],"tracker":"https://twitchtracker.com/schrodingerkitten/games/541516517","didDemo":true,"didLaunch":true,"hasSignalBoost":true,"hasLinkSync":true,"hasLaunchSupport":true,"socialTouchpoints":3,"largeProfile":false},
  {"creator":"Plabs_","status":"Done","tier":"Bronze","language":"English","followers":457,"topPct":4.18,"langRank":146985,"histAvg":7.3,"avgViewers":4,"peakViewers":5,"hours":"2h30","hoursNum":2.5,"viewerHours":10,"demoVod":"https://www.twitch.tv/videos/2727423730","launchVod":"https://www.twitch.tv/videos/2734255865","signalBoost":"https://www.youtube.com/shorts/sq8HyPvGqVM","linkSyncProofs":[],"launchSupportProofs":[],"bonusPosts":[],"tracker":"https://sullygnome.com/channel/plabs_/stream/317533338101","didDemo":true,"didLaunch":true,"hasSignalBoost":true,"hasLinkSync":false,"hasLaunchSupport":true,"socialTouchpoints":2,"largeProfile":false},
  {"creator":"Gshiba","status":"Done","tier":"Silver","language":"Portuguese","followers":6207,"topPct":0.28,"langRank":1244,"histAvg":83.6,"avgViewers":100,"peakViewers":117,"hours":"2h00","hoursNum":2,"viewerHours":200,"demoVod":"https://www.twitch.tv/videos/2737127989?t=1h41m56s","launchVod":"","signalBoost":"https://www.tiktok.com/@gshiba13/video/7623890984384105749","linkSyncProofs":[],"launchSupportProofs":[],"bonusPosts":[],"tracker":"https://twitchtracker.com/gshiba/streams/317555282038","didDemo":true,"didLaunch":false,"hasSignalBoost":true,"hasLinkSync":false,"hasLaunchSupport":false,"socialTouchpoints":1,"largeProfile":false},
];
