import type { Metadata } from "next";
import LegalPage, { type LegalBlock } from "@/app/components/LegalPage";

export const metadata: Metadata = {
  title: "Terms and Conditions",
  description:
    "Terms governing access to and use of StreamQuest, including the website, Creator Dashboard, client tools, campaign pages, Quest applications, Mission Briefs, submissions, and related services.",
  alternates: { canonical: "/terms-and-conditions" },
};

const blocks: LegalBlock[] = [
  { tag: "h2", text: "Quick summary" },
  { tag: "p", text: "These Terms govern access to and use of StreamQuest. Your dashboard sign-in flow already captures agreement before access. These Terms mirror that process and add the full detail." },
  { tag: "h2", text: "Contents" },
  { tag: "h2", text: "1. Acceptance and Scope" },
  { tag: "p", text: "These Terms and Conditions (“Terms”) govern your access to and use of StreamQuest, including the StreamQuest website, Creator Dashboard, campaign pages, Quest application flow, client services portal, submission tools, reporting features, communications, and related services (together, the “Platform” or “Services”)." },
  { tag: "p", text: "The Platform is operated by StreamQuest, registered in the Netherlands under Chamber of Commerce number 85562769 (“StreamQuest”, “we”, “us”, or “our”)." },
  { tag: "p", text: "By creating an account, checking the Terms and Conditions and Privacy Policy checkbox during sign-in, logging into the Creator Dashboard, connecting Twitch or another supported account, applying to a Quest, accepting a Mission Brief, submitting deliverables, or otherwise using the Platform, you agree to these Terms." },
  { tag: "p", text: "If you use StreamQuest on behalf of a company, publisher, studio, or other organization, you represent that you have authority to bind that entity to these Terms." },
  { tag: "h2", text: "2. Definitions" },
  { tag: "ul", items: ["Creator means an independent streamer, influencer, or content creator who applies to or participates in Quests or campaigns.", "Client, Brand, or Campaign Holder means a business or individual that instructs, funds, or runs a campaign through StreamQuest.", "Quest or Campaign means a promotional activation, streaming task, creator mission, or related opportunity published or administered through StreamQuest.", "Mission Brief means the campaign-specific rules, deadlines, deliverables, payout conditions, approved talking points, side quests, and special instructions for a Quest.", "Submission means any VOD, clip, social post, link, screenshot, proof, timestamp, or other material provided to complete or verify a Quest.", "User means any visitor, creator, client, or other person using the Platform."] },
  { tag: "h2", text: "3. Eligibility and Accounts" },
  { tag: "ul", items: ["You must be at least 18 years old, or the age of legal majority in your jurisdiction if higher, to use the Platform.", "You must provide accurate, current, and complete registration information and keep it updated.", "Creators may only access the Creator Dashboard after affirmatively accepting the applicable Terms and Privacy Policy during sign-in.", "Creators must connect a valid Twitch account, and StreamQuest may support additional platforms over time.", "You are responsible for account security, login credentials, and all activity under your account.", "You may not register using false identity information, inflated metrics, impersonation, or unauthorized access methods.", "We may request additional information to verify identity, ownership of connected accounts, legal compliance, payout readiness, or campaign suitability.", "We may restrict or deny access where we identify fraud risk, abuse risk, sanctions risk, payment risk, account duplication, repeated non-performance, or other material platform risk."] },
  { tag: "h2", text: "4. Connected Platforms" },
  { tag: "p", text: "StreamQuest may rely on third-party services such as Twitch, Discord, Stripe, PayPal, bank transfer providers, or other tools needed for authentication, campaign operations, reporting, and payouts." },
  { tag: "ul", items: ["By connecting an external account, you authorize StreamQuest to access and use account data reasonably necessary for authentication, fraud checks, creator matching, campaign verification, reporting, and support.", "This may include profile details, account identifiers, public metrics, VOD links, clips, timestamps, category information, and campaign-relevant performance indicators.", "You remain responsible for complying with the rules, policies, community guidelines, and disclosure requirements of connected third-party platforms.", "If a connected account becomes unavailable, suspended, private, disconnected, or materially altered, StreamQuest may pause, revoke, or reject campaign participation."] },
  { tag: "h2", text: "5. Quests and Mission Briefs" },
  { tag: "p", text: "StreamQuest may publish, administer, or manage Quests, streaming tasks, creator campaigns, side objectives, XP mechanics, submissions, and related campaign workflows." },
  { tag: "ul", items: ["Each Quest may include campaign-specific requirements such as timing, title/category rules, language focus, territory focus, side objectives, storefront links, social tasks, disclosure wording, and approval criteria.", "Applying to a Quest does not guarantee selection, approval, game access, a key, a slot, reimbursement, or payment.", "StreamQuest may cap participation, prioritize certain creators, waitlist creators, close campaigns early, or edit campaign details to protect quality, budget, or operational needs.", "Once a creator accepts a Mission Brief or participates in a Quest, that Mission Brief becomes binding for that campaign.", "If a signed client agreement, activation agreement, insertion order, or proposal contains more specific campaign terms, those more specific terms govern that campaign."] },
  { tag: "h2", text: "6. Creator Terms" },
  { tag: "h3", text: "6.1 Participation and compliance" },
  { tag: "ul", items: ["Creators must review the applicable Quest page and Mission Brief before participating.", "Creators must complete required deliverables accurately, on time, and in line with campaign instructions.", "Creators must use lawful, authentic, and non-misleading methods to participate.", "Creators must comply with applicable platform disclosure rules for sponsored or incentivized content.", "Where required by a Mission Brief, creators must keep VODs available, keep clips enabled, use the correct game category, and follow blackout or competitor restrictions."] },
  { tag: "h3", text: "6.2 Content standards" },
  { tag: "ul", items: ["No fake engagement, botted traffic, purchased viewers, click farms, engagement pods, or deceptive completion methods.", "No use of copyrighted or infringing materials in a way that violates third-party rights.", "No hateful, unlawful, fraudulent, harassing, threatening, sexually exploitative, or otherwise prohibited content in relation to a Quest.", "Unless a Mission Brief states a different period, approved campaign content should remain available for at least 30 days, except where removal is required by law, platform enforcement, or a valid rights complaint."] },
  { tag: "h3", text: "6.3 Creator status and responsibilities" },
  { tag: "ul", items: ["Creators participate as independent contractors or independent business users, unless mandatory law requires otherwise.", "StreamQuest is not the creator’s employer, manager, or talent agency.", "Creators are solely responsible for their own taxes, filings, invoices, local compliance obligations, and legal obligations in their jurisdiction.", "Creators are responsible for the accuracy of the data they provide, including account ownership, region, language, and audience information.", "Creators understand that Streams, VODs, clips, screenshots, timestamps, and submission records may be stored and used for verification, reporting, support, dispute resolution, or case studies."] },
  { tag: "h2", text: "7. Client Terms" },
  { tag: "ul", items: ["Clients must provide lawful, accurate, and sufficiently clear campaign materials, including goals, timelines, deliverables, approved messaging, restrictions, and assets.", "Clients represent that they have the right to provide all campaign materials, including logos, trailers, screenshots, game keys, music, press assets, and brand assets.", "Clients are responsible for ensuring their campaign instructions do not require creators or StreamQuest to violate law, platform rules, IP rights, embargoes, or advertising disclosure obligations.", "Unless otherwise agreed in writing, StreamQuest campaigns are subject to a setup fee equal to 10% of the campaign budget or €200, whichever is lower.", "Unless otherwise agreed in writing, the full campaign budget must be prepaid 5 working days before campaign start.", "Unless otherwise agreed in writing, after campaign completion the remaining budget is reconciled and reimbursed or adjusted accordingly.", "All fees and campaign budgets are in Euros, unless explicitly stated otherwise in writing.", "Because campaigns are funded upfront, StreamQuest generally does not operate late payment penalties on the creator reward portion of a campaign budget.", "Clients should review creator submissions within the review period stated in the campaign documents. If no review period is stated, 5 working days may be treated as a reasonable review window.", "If a client is unresponsive, StreamQuest may approve, close, pause, or reconcile campaign items based on available evidence and operational needs.", "Clients may not bypass StreamQuest to avoid agreed fees or to directly exploit creator introductions made through the Platform without written consent."] },
  { tag: "h2", text: "8. Verification, Payouts and Financials" },
  { tag: "p", text: "A payout only becomes earned once the required deliverables are completed, submitted, verified, compliant, and approved by StreamQuest and, where applicable, the client." },
  { tag: "ul", items: ["StreamQuest may verify submissions using VODs, timestamps, screenshots, public metrics, creator-provided proof, internal moderation, and client review.", "We may reject, downgrade, partially approve, or void a submission that is incomplete, late, misleading, off-brief, or unsupported by sufficient proof.", "Where a campaign has Bronze, Silver, XP, bonus, milestone, or other tier logic, payouts and recognition follow the rules of that specific campaign.", "Payout processing may be handled or arranged through Twitch, Stripe, PayPal, bank transfer, Revolut, donation flows, or other supported methods.", "StreamQuest is not responsible for delays caused by external payment providers, bank processing, verification checks, fraud reviews, or service outages.", "StreamQuest may withhold, reverse, offset against future payouts, or recover payments made in error or connected to fraud, invalid traffic, duplicate submissions, policy breaches, or material misrepresentation.", "Where required, creators may need to provide invoice details, payout details, or tax information before payment is released.", "Refunds for clients are generally only considered where no valid creator work has been delivered, unless a separate client agreement states otherwise."] },
  { tag: "h2", text: "9. Intellectual Property and Licenses" },
  { tag: "h3", text: "9.1 StreamQuest property" },
  { tag: "ul", items: ["StreamQuest retains all rights, title, and interest in the Platform, dashboard, workflows, XP logic, design, reports, mission formats, brand assets, trademarks, and internal tools.", "No rights are granted except as expressly stated in these Terms or a separate written agreement."] },
  { tag: "h3", text: "9.2 Creator content" },
  { tag: "ul", items: ["Creators retain ownership of their original content, subject to the licenses granted below.", "By submitting or completing approved campaign work, the creator grants StreamQuest and the relevant client a non-exclusive, worldwide, royalty-free, sublicensable license to host, store, reproduce, repost, crop, caption, subtitle, localize, distribute, display, and use the approved deliverables for campaign execution, reporting, storefront support, social media, websites, decks, case studies, internal training, and paid media.", "Unless explicitly agreed in writing, this license does not include use of creator content for standalone AI model training."] },
  { tag: "h3", text: "9.3 Client assets" },
  { tag: "ul", items: ["Clients retain ownership of their own assets, brands, logos, trailers, game keys, screenshots, and press materials.", "Clients grant StreamQuest the right to use client-provided assets as reasonably necessary to operate, market, and report on the campaign."] },
  { tag: "h3", text: "9.4 Feedback" },
  { tag: "ul", items: ["If you provide feedback, ideas, campaign learnings, or feature requests, StreamQuest may use them without restriction or compensation unless otherwise agreed in writing."] },
  { tag: "h2", text: "10. Data Access, Privacy and Transparency" },
  { tag: "p", text: "StreamQuest processes personal and business-related data in connection with authentication, campaign administration, fraud prevention, support, reporting, legal compliance, and platform operations. More detailed processing information is described in the StreamQuest Privacy Policy." },
  { tag: "h3", text: "10.1 Categories of data we may access or generate" },
  { tag: "ul", items: ["Account data such as name, email, Discord handle, connected platform identifiers, account status, and login history.", "Campaign data such as applications, approvals, rejections, VOD links, timestamps, screenshots, deliverables, proof of completion, and payout status.", "Public or platform-available performance data such as follower counts, stream duration, category, language, average CCV, clip availability, and other campaign-relevant indicators.", "Operational and anti-fraud data such as device or browser data, account change history, duplication checks, IP logs where applicable, risk flags, and payment/compliance checks."] },
  { tag: "h3", text: "10.2 Who sees what" },
  { tag: "ul", items: ["Creators generally have access to their own dashboard information, participation status, and payout status.", "Clients generally receive campaign reporting, approved deliverables, links, screenshots, timestamps, and performance summaries relevant to the campaign.", "Clients do not automatically receive unrestricted access to all creator account data. StreamQuest may limit data access to what is reasonably necessary for campaign execution, verification, and reporting."] },
  { tag: "h3", text: "10.3 Ranking, sorting, and prioritisation" },
  { tag: "ul", items: ["Where StreamQuest sorts, recommends, ranks, or prioritises creators or campaigns, relevant factors may include account validity, audience fit, language, geography, category fit, average CCV, prior completion reliability, fraud signals, content safety, timing, and client or campaign requirements.", "No user is guaranteed selection, ranking position, homepage placement, editorial featuring, or ongoing campaign visibility."] },
  { tag: "h3", text: "10.4 Retention and rights" },
  { tag: "ul", items: ["After account closure or campaign completion, StreamQuest may retain records reasonably necessary for legal, tax, accounting, security, dispute, anti-fraud, archival, and business reporting purposes.", "Where GDPR or similar laws apply, users may have rights of access, rectification, erasure, restriction, portability, objection, and complaint to a supervisory authority."] },
  { tag: "h2", text: "11. Prohibited Conduct" },
  { tag: "p", text: "Users must not, directly or indirectly:" },
  { tag: "ul", items: ["violate applicable law, privacy law, IP law, sanctions rules, export controls, ad disclosure rules, or third-party platform rules;", "submit fake, inflated, botted, manipulated, or artificially boosted traffic or engagement;", "misrepresent identity, ownership of accounts, audience, region, language, or campaign performance;", "upload malicious code, scraping tools intended to abuse the Platform, or other harmful technical interference;", "harass, threaten, dox, stalk, defame, discriminate against, or otherwise abuse another user, creator, client, or StreamQuest representative;", "circumvent StreamQuest fees, bypass the Platform to avoid agreed compensation, or otherwise interfere with campaign integrity;", "use the Platform to promote illegal goods, illegal services, infringing content, scams, or unlawful activity."] },
  { tag: "h2", text: "12. Suspension and Termination" },
  { tag: "ul", items: ["We may restrict, suspend, reject, or terminate access to all or part of the Platform where we reasonably believe a user has breached these Terms, a Mission Brief, a related agreement, applicable law, or third-party platform rules.", "We may also act to protect campaign integrity, creator safety, client safety, rights holders, payment processors, legal compliance, or StreamQuest’s reputation.", "Examples include fraud, invalid traffic, abusive conduct, IP complaints, repeated no-shows, sanctions risk, chargebacks, or unsafe content.", "We may remove a creator from a campaign before or after approval if eligibility changes, risk concerns emerge, account linking fails, or campaign scope changes.", "Unless immediate action is required for legal, fraud, safety, security, or abuse reasons, StreamQuest will try to communicate the main reason for a material restriction or suspension."] },
  { tag: "h2", text: "13. Third-Party Services" },
  { tag: "ul", items: ["The Platform may integrate with or rely on third-party services including Twitch, Discord, Stripe, Steam, payment providers, analytics services, email tools, hosting services, or other external tools.", "Those services are controlled by their own terms, policies, and technical availability.", "StreamQuest is not responsible for third-party outages, API changes, access revocations, payment delays, or platform moderation decisions outside its control."] },
  { tag: "h2", text: "14. Disclaimers and Limitation of Liability" },
  { tag: "p", text: "The Platform and Services are provided on an “as is” and “as available” basis to the fullest extent permitted by law." },
  { tag: "ul", items: ["StreamQuest does not warrant uninterrupted availability, error-free operation, guaranteed client demand, guaranteed creator selection, guaranteed earnings, or guaranteed performance outcomes.", "To the fullest extent permitted by law, StreamQuest is not liable for indirect, incidental, consequential, special, exemplary, or punitive damages, including lost profits, lost revenue, lost goodwill, lost data, or lost business opportunity.", "To the fullest extent permitted by law, StreamQuest’s aggregate liability arising out of or relating to the Services will not exceed the total amount of service fees paid by a client to StreamQuest, or the total amount of payouts actually paid by StreamQuest to a creator, during the 12 months preceding the event giving rise to the claim, with a minimum floor of €100.", "Nothing in these Terms excludes or limits liability that cannot lawfully be excluded under applicable law."] },
  { tag: "h2", text: "15. Indemnity" },
  { tag: "p", text: "To the fullest extent permitted by law, you agree to defend, indemnify, and hold harmless StreamQuest, its owner, staff, contractors, and affiliates from and against claims, losses, liabilities, costs, and expenses, including reasonable legal fees, arising out of or related to:" },
  { tag: "ul", items: ["your breach of these Terms, a Mission Brief, or a related agreement;", "your unlawful conduct, fraud, invalid traffic, or deceptive practices;", "your content, deliverables, or assets infringing IP, privacy, publicity, or other third-party rights; or", "your violation of platform rules, disclosure rules, or applicable law."] },
  { tag: "h2", text: "16. Changes to These Terms" },
  { tag: "ul", items: ["StreamQuest may update these Terms from time to time.", "The current version will be posted on the website with an updated “Last updated” date.", "Where appropriate, StreamQuest may also provide notice by email, dashboard notice, or another durable communication method.", "Where required by applicable law or where changes materially affect business users, StreamQuest will aim to provide advance notice before material changes take effect, unless faster action is required for legal, fraud, abuse, or security reasons.", "Continued use of the Platform after the effective date of updated Terms means you accept the updated Terms."] },
  { tag: "h2", text: "17. Governing Law, Complaints and Contact" },
  { tag: "ul", items: ["These Terms are governed by the laws of the Netherlands, excluding conflict of law rules, except where mandatory law requires otherwise.", "The competent courts in the Netherlands, and where validly agreed the courts of Rotterdam, shall have jurisdiction over disputes arising out of or relating to these Terms.", "Before starting formal proceedings, the parties should first attempt to resolve the matter informally and in good faith.", "If any provision of these Terms is found unenforceable, the remaining provisions remain in effect.", "Failure to enforce any provision is not a waiver.", "StreamQuest may assign these Terms in connection with a merger, reorganisation, business transfer, or sale of assets. Users may not assign their rights or obligations without prior written consent.", "Delays caused by force majeure, service outages, war, labour disruptions, supplier failures, government action, or other events outside reasonable control will not be deemed a breach."] },
];

export default function TermsAndConditionsPage() {
  return (
    <LegalPage
      eyebrow="Legal"
      title="Terms and Conditions"
      intro="These Terms govern access to and use of StreamQuest — the website, Creator Dashboard, client tools, campaign pages, Quest applications, Mission Briefs, submissions, reporting, and related services."
      lastUpdated="May 2026"
      blocks={blocks}
    />
  );
}
