/**
 * Endix May Showcase 2026 — creator submission dataset.
 * Sourced from the final Endix Creators List 2026 export.
 */

export type Status = "completed" | "missing" | "late";

export type EndixRow = {
  order: string;
  creator: string;
  status: string;
  statusClass: Status;
  tier: string;
  topPct: string;
  followers: number | null;
  avgCCV: number | null;
  langRank: string;
  language: string;
  avgViewers: number | null;
  peakViewers: number | null;
  hours: string;
  hoursNum: number;
  viewerHours: number;
  uniqueViewers: number | null;
  vod: string;
  twitchtracker: string;
  photobooth: string;
  expoClip: string;
  wishlist: string;
  payment: string;
  notes: string;
};

const langFromRank = (s: string): string => {
  const m = s.match(/[A-Za-z]+/g);
  return m ? m[m.length - 1] : "";
};

export const rows: EndixRow[] = [
  { order: "1",  creator: "ShockAndAwh",        status: "Completed", statusClass: "completed", tier: "Bronze", topPct: "2%",     followers: 1030,  avgCCV: 14,   langRank: "62152 English",     language: "English",     avgViewers: 10,  peakViewers: 12,  hours: "2h35", hoursNum: 2.58, viewerHours: 25.8,  uniqueViewers: 60,  vod: "https://www.twitch.tv/videos/2779908725",                       twitchtracker: "https://twitchtracker.com/shockandawh/streams/319398615385",  photobooth: "Yes", expoClip: "Yes", wishlist: "Yes", payment: "Done", notes: "" },
  { order: "2",  creator: "LordacrisPlays",     status: "Completed", statusClass: "completed", tier: "Silver", topPct: "0.53%",  followers: 1060,  avgCCV: 23,   langRank: "15379 English",     language: "English",     avgViewers: 19,  peakViewers: 25,  hours: "2h40", hoursNum: 2.67, viewerHours: 50.7,  uniqueViewers: 159, vod: "https://www.twitch.tv/videos/2778921134?t=0h50m38s",            twitchtracker: "https://twitchtracker.com/lordacrisplays/streams/315566947281", photobooth: "Yes", expoClip: "Yes", wishlist: "Yes", payment: "Done", notes: "" },
  { order: "3",  creator: "Findseloy",          status: "Completed", statusClass: "completed", tier: "Silver", topPct: "1.06%",  followers: 2463,  avgCCV: 18.1, langRank: "4143 Portuguese",   language: "Portuguese",  avgViewers: 25,  peakViewers: 46,  hours: "2h55", hoursNum: 2.92, viewerHours: 72.9,  uniqueViewers: 364, vod: "https://www.twitch.tv/videos/2778521977?t=03h56m52s",           twitchtracker: "https://twitchtracker.com/findseloy/streams/317954675446",    photobooth: "Yes", expoClip: "Yes", wishlist: "Yes", payment: "Done", notes: "" },
  { order: "4",  creator: "SweetsnCozy",        status: "Approved · non-submission", statusClass: "missing", tier: "", topPct: "", followers: null, avgCCV: null, langRank: "", language: "", avgViewers: null, peakViewers: null, hours: "", hoursNum: 0, viewerHours: 0, uniqueViewers: null, vod: "", twitchtracker: "", photobooth: "", expoClip: "", wishlist: "", payment: "", notes: "Approved creator row, no completed submission in latest tracker." },
  { order: "5",  creator: "BrunaRodrigues",     status: "Approved · non-submission", statusClass: "missing", tier: "", topPct: "", followers: null, avgCCV: null, langRank: "", language: "", avgViewers: null, peakViewers: null, hours: "", hoursNum: 0, viewerHours: 0, uniqueViewers: null, vod: "", twitchtracker: "", photobooth: "", expoClip: "", wishlist: "", payment: "", notes: "Approved creator row, no completed submission in latest tracker." },
  { order: "6",  creator: "Eyklor",             status: "Completed", statusClass: "completed", tier: "Silver", topPct: "1.45%",  followers: 511,   avgCCV: 16.9, langRank: "5027 French",       language: "French",      avgViewers: 19,  peakViewers: 26,  hours: "2h15", hoursNum: 2.25, viewerHours: 42.8,  uniqueViewers: 112, vod: "https://www.twitch.tv/videos/2780002517",                       twitchtracker: "https://twitchtracker.com/eyklor/streams/316842844771",       photobooth: "Yes", expoClip: "Yes", wishlist: "Yes", payment: "Done", notes: "" },
  { order: "7",  creator: "iMartynFox",         status: "Completed", statusClass: "completed", tier: "Silver", topPct: "1.65%",  followers: 3078,  avgCCV: 16.7, langRank: "6036 Portuguese",   language: "Portuguese",  avgViewers: 15,  peakViewers: 32,  hours: "2h06", hoursNum: 2.10, viewerHours: 31.5,  uniqueViewers: 144, vod: "https://www.twitch.tv/videos/2779024834",                       twitchtracker: "https://twitchtracker.com/imartynfox/streams/318090916212",   photobooth: "Yes", expoClip: "Yes", wishlist: "Yes", payment: "Done", notes: "" },
  { order: "8",  creator: "Stonii",             status: "Approved · non-submission", statusClass: "missing", tier: "", topPct: "", followers: null, avgCCV: null, langRank: "", language: "", avgViewers: null, peakViewers: null, hours: "", hoursNum: 0, viewerHours: 0, uniqueViewers: null, vod: "", twitchtracker: "", photobooth: "", expoClip: "", wishlist: "", payment: "", notes: "Approved creator row, no completed submission in latest tracker." },
  { order: "9",  creator: "luiiszera",          status: "Approved · non-submission", statusClass: "missing", tier: "", topPct: "", followers: null, avgCCV: null, langRank: "", language: "", avgViewers: null, peakViewers: null, hours: "", hoursNum: 0, viewerHours: 0, uniqueViewers: null, vod: "", twitchtracker: "", photobooth: "", expoClip: "", wishlist: "", payment: "", notes: "Approved creator row, no completed submission in latest tracker." },
  { order: "10", creator: "UmbritaC",           status: "Completed", statusClass: "completed", tier: "Silver", topPct: "2.2%",   followers: 2768,  avgCCV: 17.1, langRank: "112 Romanian",      language: "Romanian",    avgViewers: 15,  peakViewers: 15,  hours: "2h46", hoursNum: 2.77, viewerHours: 41.5,  uniqueViewers: 85,  vod: "https://www.twitch.tv/videos/2778271348",                       twitchtracker: "https://twitchtracker.com/umbritac/streams/317370843877",     photobooth: "Yes", expoClip: "Yes", wishlist: "Yes", payment: "Done", notes: "" },
  { order: "11", creator: "fradda",             status: "Completed", statusClass: "completed", tier: "Bronze", topPct: "4.5%",   followers: 852,   avgCCV: 6,    langRank: "18523 English",     language: "English",     avgViewers: 5,   peakViewers: 9,   hours: "1h05", hoursNum: 1.08, viewerHours: 5.4,   uniqueViewers: 47,  vod: "https://www.twitch.tv/videos/2780402779",                       twitchtracker: "https://twitchtracker.com/fradda/streams/315677012074",       photobooth: "", expoClip: "", wishlist: "", payment: "Done", notes: "" },
  { order: "12", creator: "jemplfg",            status: "Completed", statusClass: "completed", tier: "Silver", topPct: "1.8%",   followers: 564,   avgCCV: 20.9, langRank: "55487 English",     language: "English",     avgViewers: 17,  peakViewers: 24,  hours: "2h32", hoursNum: 2.53, viewerHours: 43.1,  uniqueViewers: 94,  vod: "https://www.twitch.tv/videos/2778904072",                       twitchtracker: "https://twitchtracker.com/jemplfg/games/2129224656",          photobooth: "Yes", expoClip: "Yes", wishlist: "Yes", payment: "Done", notes: "" },
  { order: "13", creator: "ToKy",               status: "Completed", statusClass: "completed", tier: "Bronze", topPct: "1.8%",   followers: 25872, avgCCV: 26.4, langRank: "55394 English",     language: "English",     avgViewers: 10,  peakViewers: 14,  hours: "2h50", hoursNum: 2.83, viewerHours: 28.3,  uniqueViewers: 51,  vod: "https://www.twitch.tv/videos/2779365424",                       twitchtracker: "https://twitchtracker.com/toky",                              photobooth: "Yes", expoClip: "https://x.com/ToKymonGrey/status/2058385942625268210", wishlist: "Yes", payment: "Done", notes: "" },
  { order: "14", creator: "BumquackZA",         status: "Completed", statusClass: "completed", tier: "Bronze", topPct: "3.95%",  followers: 218,   avgCCV: 7,    langRank: "127441 English",    language: "English",     avgViewers: 8,   peakViewers: 18,  hours: "2h50", hoursNum: 2.83, viewerHours: 22.7,  uniqueViewers: 48,  vod: "https://www.twitch.tv/videos/2778148816",                       twitchtracker: "https://twitchtracker.com/bumquackza",                        photobooth: "Yes", expoClip: "", wishlist: "", payment: "Done", notes: "" },
  { order: "15", creator: "Torynho",            status: "Approved · non-submission", statusClass: "missing", tier: "", topPct: "1.49%", followers: 2210, avgCCV: 13.6, langRank: "5487 Portuguese", language: "Portuguese", avgViewers: null, peakViewers: null, hours: "", hoursNum: 0, viewerHours: 0, uniqueViewers: null, vod: "", twitchtracker: "", photobooth: "", expoClip: "", wishlist: "", payment: "", notes: "" },
  { order: "16", creator: "Paildry",            status: "Completed", statusClass: "completed", tier: "Silver", topPct: "1.03%",  followers: 805,   avgCCV: 19,   langRank: "4721 German",       language: "German",      avgViewers: 19,  peakViewers: 25,  hours: "2h15", hoursNum: 2.25, viewerHours: 42.8,  uniqueViewers: 55,  vod: "https://www.twitch.tv/videos/2778794755",                       twitchtracker: "https://twitchtracker.com/paildry/streams/317446135654",      photobooth: "Yes", expoClip: "Yes", wishlist: "https://x.com/Paildry/status/2058178172605055418", payment: "Done", notes: "" },
  { order: "17", creator: "Savage_Kai",         status: "Completed", statusClass: "completed", tier: "Silver", topPct: "3.74%",  followers: 1521,  avgCCV: 12.7, langRank: "120579 English",    language: "English",     avgViewers: 15,  peakViewers: 18,  hours: "2h32", hoursNum: 2.53, viewerHours: 38.0,  uniqueViewers: 69,  vod: "https://www.twitch.tv/videos/2779748152",                       twitchtracker: "https://twitchtracker.com/savage_kai/statistics",             photobooth: "Yes", expoClip: "Yes", wishlist: "Yes", payment: "Done", notes: "" },
  { order: "18", creator: "Shalalaka",          status: "Approved · non-submission", statusClass: "missing", tier: "", topPct: "0.34%", followers: 14150, avgCCV: 37.3, langRank: "1448 Portuguese", language: "Portuguese", avgViewers: null, peakViewers: null, hours: "", hoursNum: 0, viewerHours: 0, uniqueViewers: null, vod: "", twitchtracker: "", photobooth: "", expoClip: "", wishlist: "", payment: "", notes: "" },
  { order: "19", creator: "Soullessiren",       status: "Approved · non-submission", statusClass: "missing", tier: "", topPct: "", followers: null, avgCCV: null, langRank: "", language: "", avgViewers: null, peakViewers: null, hours: "", hoursNum: 0, viewerHours: 0, uniqueViewers: null, vod: "", twitchtracker: "", photobooth: "", expoClip: "", wishlist: "", payment: "", notes: "Approved creator row, no completed submission in latest tracker." },
  { order: "20", creator: "PearDoll",           status: "Completed", statusClass: "completed", tier: "Bronze", topPct: "5.4%",   followers: 700,   avgCCV: 8,    langRank: "128126 English",    language: "English",     avgViewers: 5,   peakViewers: 9,   hours: "2h17", hoursNum: 2.28, viewerHours: 11.4,  uniqueViewers: 21,  vod: "https://www.twitch.tv/videos/2779920318?t=00h06m07s",           twitchtracker: "",                                                              photobooth: "", expoClip: "", wishlist: "", payment: "Done", notes: "" },
  { order: "21", creator: "TattyHikari",        status: "Completed", statusClass: "completed", tier: "Silver", topPct: "0.6%",   followers: 4761,  avgCCV: 37.3, langRank: "2342 Portuguese",   language: "Portuguese",  avgViewers: 27,  peakViewers: 45,  hours: "5h",   hoursNum: 5.00, viewerHours: 135.0, uniqueViewers: 404, vod: "https://www.twitch.tv/videos/2779404747",                       twitchtracker: "https://twitchtracker.com/tattyhikari/streams/318035530229",  photobooth: "Yes", expoClip: "https://www.tiktok.com/@tattyhikari/video/7643525314835991809", wishlist: "https://www.instagram.com/p/DYs3QFalSHx/", payment: "Done", notes: "" },
  { order: "22", creator: "LunariValkyrie",     status: "Completed", statusClass: "completed", tier: "Silver", topPct: "1.32%",  followers: 16192, avgCCV: 18.3, langRank: "39969 English",     language: "English",     avgViewers: 22,  peakViewers: 28,  hours: "2h24", hoursNum: 2.40, viewerHours: 52.8,  uniqueViewers: 400, vod: "https://www.twitch.tv/videos/2778707471",                       twitchtracker: "https://twitchtracker.com/lunarivalkyrie/streams/317195228376", photobooth: "Yes", expoClip: "https://www.tiktok.com/@lunarivalkyrie/video/7643066189379325197", wishlist: "https://bsky.app/profile/lunarivalkyrie.bsky.social/post/3mmjavtoagk26", payment: "Done", notes: "" },
  { order: "23", creator: "Phenexa",            status: "Completed", statusClass: "completed", tier: "Silver", topPct: "1.11%",  followers: 3577,  avgCCV: 21.4, langRank: "33218 English",     language: "English",     avgViewers: 19,  peakViewers: 27,  hours: "3h02", hoursNum: 3.03, viewerHours: 57.6,  uniqueViewers: 83,  vod: "https://www.twitch.tv/videos/2779154602?t=00h28m02s",           twitchtracker: "https://twitchtracker.com/phenexa/streams/317237246823",      photobooth: "Yes", expoClip: "Yes", wishlist: "https://x.com/OfficialPhenexa/status/2058262365288763437", payment: "Done", notes: "" },
  { order: "24", creator: "Hinogashy",          status: "Completed", statusClass: "completed", tier: "Silver", topPct: "0.52%",  followers: 6728,  avgCCV: 17.3, langRank: "2050 Portuguese",   language: "Portuguese",  avgViewers: 21,  peakViewers: 45,  hours: "2h40", hoursNum: 2.67, viewerHours: 56.0,  uniqueViewers: 215, vod: "https://www.twitch.tv/videos/2779342611?t=0h24m24s",            twitchtracker: "https://twitchtracker.com/hinogashy/streams/317962882294",    photobooth: "Yes", expoClip: "Yes", wishlist: "https://x.com/Hinogashy/status/2058457730969456729", payment: "Done", notes: "" },
  { order: "25", creator: "HaouAnubis",         status: "Completed", statusClass: "completed", tier: "Silver", topPct: "2.18%",  followers: 540,   avgCCV: 29.2, langRank: "68105 English",     language: "English",     avgViewers: 30,  peakViewers: 33,  hours: "2h03", hoursNum: 2.05, viewerHours: 61.5,  uniqueViewers: 319, vod: "https://www.twitch.tv/videos/2779854448",                       twitchtracker: "https://twitchtracker.com/haouanubis/streams/316825304676",   photobooth: "Yes", expoClip: "Yes", wishlist: "", payment: "Done", notes: "" },
  { order: "26", creator: "halios",             status: "Approved · non-submission", statusClass: "missing", tier: "", topPct: "", followers: 5198, avgCCV: 7.1, langRank: "112451 English", language: "English", avgViewers: null, peakViewers: null, hours: "", hoursNum: 0, viewerHours: 0, uniqueViewers: null, vod: "", twitchtracker: "", photobooth: "", expoClip: "", wishlist: "", payment: "", notes: "" },
  { order: "27", creator: "TvSerious",          status: "Approved · non-submission", statusClass: "missing", tier: "", topPct: "0.98%", followers: 21901, avgCCV: 26.8, langRank: "3812 Portuguese", language: "Portuguese", avgViewers: null, peakViewers: null, hours: "", hoursNum: 0, viewerHours: 0, uniqueViewers: null, vod: "", twitchtracker: "", photobooth: "", expoClip: "", wishlist: "", payment: "", notes: "" },
  { order: "28", creator: "Capsuhi",            status: "Completed", statusClass: "completed", tier: "Bronze", topPct: "3.82%",  followers: 379,   avgCCV: 14.4, langRank: "13297 French",      language: "French",      avgViewers: 9,   peakViewers: 15,  hours: "2h13", hoursNum: 2.22, viewerHours: 20.0,  uniqueViewers: 49,  vod: "https://www.twitch.tv/videos/2778142053",                       twitchtracker: "https://twitchtracker.com/capsuhi/streams/316827294179",      photobooth: "Yes", expoClip: "Yes", wishlist: "Yes", payment: "Done", notes: "" },
  { order: "29", creator: "Uclaoboat",          status: "Completed", statusClass: "completed", tier: "Silver", topPct: "",       followers: null,  avgCCV: null, langRank: "",                  language: "",            avgViewers: 21,  peakViewers: 25,  hours: "2h15", hoursNum: 2.25, viewerHours: 47.2,  uniqueViewers: 350, vod: "https://www.twitch.tv/videos/2779400162?t=00h24m19s",           twitchtracker: "https://twitchtracker.com/uclaoboat",                         photobooth: "Yes", expoClip: "Yes", wishlist: "Yes", payment: "Done", notes: "" },
  { order: "30", creator: "VitoriaRoleplay",    status: "Approved · non-submission", statusClass: "missing", tier: "", topPct: "", followers: null, avgCCV: null, langRank: "", language: "", avgViewers: null, peakViewers: null, hours: "", hoursNum: 0, viewerHours: 0, uniqueViewers: null, vod: "not submitted", twitchtracker: "", photobooth: "", expoClip: "", wishlist: "", payment: "", notes: "" },
  { order: "31", creator: "ARTTT",              status: "Completed", statusClass: "completed", tier: "Silver", topPct: "0.16%",  followers: 31515, avgCCV: 67.9, langRank: "4517 English",      language: "English",     avgViewers: 81,  peakViewers: 84,  hours: "2h08", hoursNum: 2.13, viewerHours: 172.8, uniqueViewers: 894, vod: "https://www.twitch.tv/videos/2780130904",                       twitchtracker: "https://twitchtracker.com/arttt/streams/318042447861",        photobooth: "Yes", expoClip: "Yes", wishlist: "", payment: "Done", notes: "" },
  { order: "32", creator: "Maveco",             status: "Completed", statusClass: "completed", tier: "Silver", topPct: "1.82%",  followers: 12068, avgCCV: 18.2, langRank: "6539 Portuguese",   language: "Portuguese",  avgViewers: 20,  peakViewers: 24,  hours: "2h30", hoursNum: 2.50, viewerHours: 50.0,  uniqueViewers: 187, vod: "https://www.twitch.tv/videos/2779838634?t=5h1m33s",             twitchtracker: "https://twitchtracker.com/maveco/games/2129224656",           photobooth: "Yes", expoClip: "Yes", wishlist: "Yes", payment: "Done", notes: "" },
  { order: "33", creator: "Elllandria",         status: "Completed", statusClass: "completed", tier: "Silver", topPct: "0.35%",  followers: 7556,  avgCCV: 46.8, langRank: "1513 Portuguese",   language: "Portuguese",  avgViewers: 21,  peakViewers: 35,  hours: "2h18", hoursNum: 2.30, viewerHours: 48.3,  uniqueViewers: 177, vod: "https://www.twitch.tv/videos/2778909153",                       twitchtracker: "https://twitchtracker.com/elllandria/games/2129224656",       photobooth: "Yes", expoClip: "Yes", wishlist: "", payment: "Done", notes: "" },
  { order: "34", creator: "UndoubtedlyLink",    status: "Completed", statusClass: "completed", tier: "Silver", topPct: "1.18%",  followers: 2230,  avgCCV: 29,   langRank: "35554 English",     language: "English",     avgViewers: 30,  peakViewers: 35,  hours: "2h00", hoursNum: 2.00, viewerHours: 60.0,  uniqueViewers: null, vod: "https://www.twitch.tv/videos/2779329358",                       twitchtracker: "https://twitchtracker.com/undoubtedlylink/streams/317454901222", photobooth: "Yes", expoClip: "Yes", wishlist: "Yes", payment: "Done", notes: "Duration counted conservatively as 2h00 for KPI math." },
  { order: "35", creator: "fleapuff",           status: "Approved · non-submission", statusClass: "missing", tier: "", topPct: "", followers: null, avgCCV: null, langRank: "", language: "", avgViewers: null, peakViewers: null, hours: "", hoursNum: 0, viewerHours: 0, uniqueViewers: null, vod: "", twitchtracker: "", photobooth: "", expoClip: "", wishlist: "", payment: "", notes: "Approved creator row, no completed submission in latest tracker." },
  { order: "36", creator: "ScorpiNhoO",         status: "Completed", statusClass: "completed", tier: "Silver", topPct: "0.73%",  followers: 963,   avgCCV: 8.8,  langRank: "2938 Portuguese",   language: "Portuguese",  avgViewers: 17,  peakViewers: 25,  hours: "4h20", hoursNum: 4.33, viewerHours: 73.7,  uniqueViewers: 150, vod: "https://www.twitch.tv/videos/2780153943",                       twitchtracker: "https://twitchtracker.com/scorpinhoo/games/2129224656",       photobooth: "https://www.youtube.com/watch?v=LZqRRz29IvY", expoClip: "https://www.youtube.com/shorts/BjaGljey2oc", wishlist: "https://www.instagram.com/p/DYvvByfva-X/", payment: "Done", notes: "" },
  { order: "37", creator: "Paschoalin",         status: "Completed", statusClass: "completed", tier: "Silver", topPct: "1.17%",  followers: 4796,  avgCCV: 14.6, langRank: "4499 Portuguese",   language: "Portuguese",  avgViewers: 22,  peakViewers: 28,  hours: "3h29", hoursNum: 3.48, viewerHours: 76.6,  uniqueViewers: 172, vod: "https://www.twitch.tv/videos/2779244643?t=00h05m40s",           twitchtracker: "https://twitchtracker.com/paschoalin/streams/318033030261",   photobooth: "Yes", expoClip: "Yes", wishlist: "Yes", payment: "Done", notes: "" },
  { order: "38", creator: "Deltanuxx",          status: "Completed", statusClass: "completed", tier: "Silver", topPct: "",       followers: null,  avgCCV: null, langRank: "",                  language: "",            avgViewers: 15,  peakViewers: 24,  hours: "2h30", hoursNum: 2.50, viewerHours: 37.5,  uniqueViewers: 166, vod: "https://www.twitch.tv/videos/2778590182",                       twitchtracker: "https://twitchtracker.com/deltanuxx/streams/317955577718",    photobooth: "", expoClip: "Yes", wishlist: "", payment: "Done", notes: "" },
  { order: "39", creator: "SadWrathProduction", status: "Completed", statusClass: "completed", tier: "Silver", topPct: "0.59%",  followers: 1361,  avgCCV: 30,   langRank: "2086 French",       language: "French",      avgViewers: 36,  peakViewers: 49,  hours: "2h30", hoursNum: 2.50, viewerHours: 90.0,  uniqueViewers: 255, vod: "https://www.twitch.tv/videos/2779769768",                       twitchtracker: "https://twitchtracker.com/sadwrathproduction/games/2129224656", photobooth: "Yes", expoClip: "Yes", wishlist: "", payment: "Done", notes: "" },
  { order: "40", creator: "SOGAeon",            status: "Completed", statusClass: "completed", tier: "Silver", topPct: "0.17%",  followers: null,  avgCCV: null, langRank: "",                  language: "",            avgViewers: 133, peakViewers: 149, hours: "2h10", hoursNum: 2.17, viewerHours: 288.2, uniqueViewers: null, vod: "https://www.twitch.tv/videos/2778676680",                       twitchtracker: "https://twitchtracker.com/sogaeon/streams/317852119767",      photobooth: "Yes", expoClip: "Yes", wishlist: "Yes", payment: "Done", notes: "Twitch top % updated from latest export; remaining overview fields not exposed in source." },
  { order: "41", creator: "Danelah",            status: "Approved · non-submission", statusClass: "missing", tier: "", topPct: "", followers: null, avgCCV: null, langRank: "", language: "", avgViewers: null, peakViewers: null, hours: "", hoursNum: 0, viewerHours: 0, uniqueViewers: null, vod: "", twitchtracker: "", photobooth: "", expoClip: "", wishlist: "", payment: "", notes: "Approved creator row, no completed submission in latest tracker." },
  { order: "42", creator: "Damianrojo91",       status: "Approved · non-submission", statusClass: "missing", tier: "", topPct: "", followers: null, avgCCV: null, langRank: "", language: "", avgViewers: null, peakViewers: null, hours: "", hoursNum: 0, viewerHours: 0, uniqueViewers: null, vod: "", twitchtracker: "", photobooth: "", expoClip: "", wishlist: "", payment: "", notes: "Approved creator row, no completed submission in latest tracker." },
  { order: "43", creator: "InuYashaEdwina",     status: "Approved · non-submission", statusClass: "missing", tier: "", topPct: "", followers: null, avgCCV: null, langRank: "", language: "", avgViewers: null, peakViewers: null, hours: "", hoursNum: 0, viewerHours: 0, uniqueViewers: null, vod: "", twitchtracker: "", photobooth: "", expoClip: "", wishlist: "", payment: "", notes: "Approved creator row, no completed submission in latest tracker." },
  { order: "44", creator: "SolitaireGamingg",   status: "Approved · non-submission", statusClass: "missing", tier: "", topPct: "", followers: null, avgCCV: null, langRank: "", language: "", avgViewers: null, peakViewers: null, hours: "", hoursNum: 0, viewerHours: 0, uniqueViewers: null, vod: "", twitchtracker: "", photobooth: "", expoClip: "", wishlist: "", payment: "", notes: "Approved creator row, no completed submission in latest tracker." },
  { order: "45", creator: "El_HAlo",            status: "Completed", statusClass: "completed", tier: "Silver", topPct: "",       followers: null,  avgCCV: null, langRank: "",                  language: "",            avgViewers: 15,  peakViewers: 32,  hours: "2h44", hoursNum: 2.73, viewerHours: 41.0,  uniqueViewers: 50,  vod: "https://www.twitch.tv/videos/2778624206?t=0h26m1s",             twitchtracker: "https://twitchtracker.com/el_halo/streams/318027756149",      photobooth: "Yes", expoClip: "Yes", wishlist: "", payment: "Done", notes: "" },
  { order: "46", creator: "evelina_2",          status: "Approved · non-submission", statusClass: "missing", tier: "", topPct: "", followers: null, avgCCV: null, langRank: "", language: "", avgViewers: null, peakViewers: null, hours: "", hoursNum: 0, viewerHours: 0, uniqueViewers: null, vod: "", twitchtracker: "", photobooth: "", expoClip: "", wishlist: "", payment: "", notes: "Approved creator row, no completed submission in latest tracker." },
  { order: "47", creator: "sbuddypoke",         status: "Completed", statusClass: "completed", tier: "Silver", topPct: "",       followers: null,  avgCCV: null, langRank: "",                  language: "",            avgViewers: 32,  peakViewers: 43,  hours: "2h27", hoursNum: 2.45, viewerHours: 78.4,  uniqueViewers: 200, vod: "https://www.twitch.tv/videos/2780153201?t=0h12m9s",             twitchtracker: "https://twitchtracker.com/sbuddypoke/streams/317971181430",   photobooth: "Yes", expoClip: "Yes", wishlist: "", payment: "Done", notes: "" },
  { order: "48", creator: "MeisYouNo",          status: "Approved · non-submission", statusClass: "missing", tier: "", topPct: "", followers: null, avgCCV: null, langRank: "", language: "", avgViewers: null, peakViewers: null, hours: "", hoursNum: 0, viewerHours: 0, uniqueViewers: null, vod: "", twitchtracker: "", photobooth: "", expoClip: "", wishlist: "", payment: "", notes: "Approved creator row, no completed submission in latest tracker." },
  { order: "49", creator: "Cosminhas2",         status: "Completed", statusClass: "completed", tier: "Silver", topPct: "",       followers: null,  avgCCV: null, langRank: "",                  language: "",            avgViewers: 21,  peakViewers: 37,  hours: "2h09", hoursNum: 2.15, viewerHours: 45.1,  uniqueViewers: 179, vod: "https://www.twitch.tv/videos/2779222291",                       twitchtracker: "https://twitchtracker.com/cosminhas2/streams/318032747893",   photobooth: "", expoClip: "Yes", wishlist: "", payment: "Done", notes: "" },
  { order: "Late-1", creator: "VireoArcade",   status: "Applied · campaign full", statusClass: "late", tier: "", topPct: "", followers: null, avgCCV: null, langRank: "", language: "", avgViewers: null, peakViewers: null, hours: "", hoursNum: 0, viewerHours: 0, uniqueViewers: null, vod: "", twitchtracker: "", photobooth: "", expoClip: "", wishlist: "", payment: "", notes: "Applied after selection was full." },
  { order: "Late-2", creator: "DJCatCannon",    status: "Applied · campaign full", statusClass: "late", tier: "", topPct: "", followers: null, avgCCV: null, langRank: "", language: "", avgViewers: null, peakViewers: null, hours: "", hoursNum: 0, viewerHours: 0, uniqueViewers: null, vod: "", twitchtracker: "", photobooth: "", expoClip: "", wishlist: "", payment: "", notes: "Applied after selection was full." },
  { order: "Late-3", creator: "TheSirSlender",  status: "Applied · campaign full", statusClass: "late", tier: "", topPct: "", followers: null, avgCCV: null, langRank: "", language: "", avgViewers: null, peakViewers: null, hours: "", hoursNum: 0, viewerHours: 0, uniqueViewers: null, vod: "", twitchtracker: "", photobooth: "", expoClip: "", wishlist: "", payment: "", notes: "Applied after selection was full." },
  { order: "Late-4", creator: "Jesucristo69x",  status: "Applied · campaign full", statusClass: "late", tier: "", topPct: "", followers: null, avgCCV: null, langRank: "", language: "", avgViewers: null, peakViewers: null, hours: "", hoursNum: 0, viewerHours: 0, uniqueViewers: null, vod: "", twitchtracker: "", photobooth: "", expoClip: "", wishlist: "", payment: "", notes: "Applied after selection was full." },
  { order: "Late-5", creator: "Denzaay",        status: "Applied · campaign full", statusClass: "late", tier: "", topPct: "", followers: null, avgCCV: null, langRank: "", language: "", avgViewers: null, peakViewers: null, hours: "", hoursNum: 0, viewerHours: 0, uniqueViewers: null, vod: "", twitchtracker: "", photobooth: "", expoClip: "", wishlist: "", payment: "", notes: "Applied after selection was full." },
  { order: "Late-6", creator: "igorek_games",   status: "Applied · campaign full", statusClass: "late", tier: "", topPct: "", followers: null, avgCCV: null, langRank: "", language: "", avgViewers: null, peakViewers: null, hours: "", hoursNum: 0, viewerHours: 0, uniqueViewers: null, vod: "", twitchtracker: "", photobooth: "", expoClip: "", wishlist: "", payment: "", notes: "Applied after selection was full." },
  { order: "Late-7", creator: "MacASnack",      status: "Applied · campaign full", statusClass: "late", tier: "", topPct: "", followers: null, avgCCV: null, langRank: "", language: "", avgViewers: null, peakViewers: null, hours: "", hoursNum: 0, viewerHours: 0, uniqueViewers: null, vod: "", twitchtracker: "", photobooth: "", expoClip: "", wishlist: "", payment: "", notes: "Applied after selection was full." },
  { order: "Late-8", creator: "Chefskullz",     status: "Applied · campaign full", statusClass: "late", tier: "", topPct: "", followers: null, avgCCV: null, langRank: "", language: "", avgViewers: null, peakViewers: null, hours: "", hoursNum: 0, viewerHours: 0, uniqueViewers: null, vod: "", twitchtracker: "", photobooth: "", expoClip: "", wishlist: "", payment: "", notes: "Applied after selection was full." },
];

export const reconciliation = {
  totalApplications: 75,
  named: rows.length,
  unnamedApproved: 11,
  unnamedOpen: 7,
};
